- Gemfile
- gemfiles/default-with-activesupport.gemfile
- gemfiles/json.gemfile
- gemfiles/yajl.gemfile
This should fix the travis build for 1.8.7 and 1.9.2.
> Force an older version of the i18n gem for Ruby < 1.9.3

- lib/stripe/api_operations/delete.rb
> Pass along API key

- lib/stripe/application_fee.rb
> Pass along api_key when refunding fees

- lib/stripe/card.rb
- test/stripe/customer_card_test.rb
- test/stripe/recipient_card_test.rb
- test/test_data.rb
> card management should use the sources endpoint

- lib/stripe/api_operations/update.rb
- lib/stripe/stripe_object.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
r? @russelldavis 
This is analogous to https://github.com/stripe/stripe-python/pull/126/files
> Fix updating for nested hashes

- test/stripe/account_test.rb
> Add a test for retrieving accounts using an API key as the only param

- .travis.yml
> Run tests on jruby in 1.9 mode.

- lib/stripe/util.rb
- test/stripe/charge_test.rb
> Requests with arrays of dictionaries now properly work

- lib/stripe.rb
- test/stripe/api_resource_test.rb
> Add configurable timeouts. [#265]

- lib/stripe/list_object.rb
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- test/stripe/api_resource_test.rb
Hi there,
I opened issue #223 a couple weeks ago.  I never got any feedback, so I apologize if this is an unwelcome change.  Anyway, it fixes the issue I had and, to the best of my knowledge, doesn't break anything else.  So I'm submitting this for review, thanks
> fix #223 support expansions when retrieving via ListObject

- lib/stripe/account.rb
> Added the ability to delete an account

- lib/stripe.rb
- lib/stripe/dispute.rb
- lib/stripe/util.rb
- test/stripe/dispute_test.rb
- test/test_data.rb
r? @kyleconroy cc @russelldavis
> Add top level dispute methods.

- lib/stripe/customer.rb
* Permit easy pagination for example
> Allow params when retrieving customer objects

- lib/stripe.rb
- lib/stripe/errors/rate_limit_error.rb
- test/stripe/api_resource_test.rb
- test/test_data.rb
> add 429 rate limit error

- lib/stripe/product.rb
- test/stripe/order_test.rb
> Fix hash literal for backwards compatibility.

- test/test_data.rb
> Fix fixture data for invoices (and specifically invoice items)

- lib/stripe/account.rb
- lib/stripe/stripe_object.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
r? @russelldavis 
Addresses #284
> Disallow directly overriding legal_entity

- lib/stripe/list_object.rb
- Addresses a bit of duplication.
> ListObject extends ApiOperations::Create

- lib/stripe/charge.rb
- test/stripe/charge_refund_test.rb
> Forward parameters passed to charge.refund

- lib/stripe/product.rb
- lib/stripe/sku.rb
- test/stripe/product_test.rb
- test/stripe/sku_test.rb
> Support deleting SKUs and products.

- lib/stripe/charge.rb
- test/stripe/charge_test.rb
An unfortunate side effect of #364 is that it broke compatibility for
users on very old API versions because their `refunds` field will come
back as an array.
This adds a compatibility layer that will allow even users on old API
versions to seamlessly upgrade their gem versions.
~~@remistr Mind taking a look at this one? If you compare the new code to the
removed code in #364, you'll see that's essentially identical. Thanks!~~
> Provide compatibility patch the Charge#refund helper

- lib/stripe.rb
- lib/stripe/alipay_account.rb
- lib/stripe/util.rb
- test/stripe/alipay_account_test.rb
This adds the ability to retrieve an Alipay account properly and delete it
r? @stripe/api-libraries
> Support AlipayAccount retrieval and deletion

- stripe.gemspec
> Fix homepage for Ruby docs in gemspec

- lib/stripe.rb
- lib/stripe/three_d_secure.rb
- lib/stripe/util.rb
- test/stripe/three_d_secure_test.rb
- test/test_data.rb
r? @brandur 
cc @stripe/api-libraries @bct
Support for the new server-side 3D Secure API (currently in private beta).
> Added support for 3D Secure

- lib/stripe.rb
- lib/stripe/source.rb
- test/stripe/source_test.rb
This PR adds the ability to create and retrieve Source objects
> Add Source functionality

- lib/stripe/source.rb
Adding the ability to create source objects
> Add ability to create sources

- lib/stripe.rb
Right now we are retrying *most* non-HTTP exceptions. This is
problematic because in something like a test context, even a rogue name
error could initiate a retry. It's also bad for production because there
are quite a number of socket errors [1] for which we don't want to
retry.
Fixes #462.
[1] https://ruby-doc.org/stdlib-2.3.0/libdoc/socket/rdoc/Socket.html
> Whitelist retry exceptions

- lib/stripe/subscription.rb
- lib/stripe/util.rb
- test/stripe/subscription_test.rb
- test/stripe/util_test.rb
Also add a new `array_to_hash` function.
> Correctly encode the subscription items array

- lib/stripe.rb
- lib/stripe/errors/permissions_error.rb
- test/stripe/api_resource_test.rb
> Handle 403 status codes

- lib/stripe/util.rb
Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co
> Minor Fixes

- lib/stripe/stripe_object.rb
Fixes a memory leak caused by a doubled up `instance_eval`. See [1] for
context and discussion.
r? @dpetrovics
Fixes #477.
[1] https://github.com/stripe/stripe-ruby/issues/477
> Fix memory leak

- lib/stripe/three_d_secure.rb
- test/stripe/three_d_secure_test.rb
cc @stripe/api-libraries @bct 
Adds a method for retrieving 3DS auths.
> Adds 3DS retrieve endpoint

- lib/stripe.rb
This one is unfortunately a lot of churn, but it's incredibly
frustrating how difficult it is to find methods in this file.
Here we alphabetize the methods, but do nothing else. Alphabetization
only occurs within visibility blocks, so visibility is not affected at
all.
> Alphabetize methods in lib/stripe.rb

- test/stripe/invoice_line_item_test.rb
This doesn't come back directly from the API so the suite is empty, but
just for completeness add a test file for the newly created
`InvoiceLineItem` model.
> Add test structure for `InvoiceLineItem`

- test/stripe/api_resource_test.rb
> Remove raw PANs and use magic tokens instead

- .rubocop_todo.yml
- Gemfile
- lib/stripe.rb
- lib/stripe/account.rb
- lib/stripe/api_operations/save.rb
- lib/stripe/api_resource.rb
- lib/stripe/invoice.rb
- lib/stripe/stripe_client.rb
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- lib/stripe/webhook.rb
- stripe.gemspec
- test/stripe/api_resource_test.rb
- test/stripe/stripe_client_test.rb
- test/stripe/stripe_object_test.rb
- test/stripe/webhook_test.rb
- test/test_helper.rb
I wanted to see what fixing Rubocop TODOs was like, so I tried to
eliminate all the easy ones. Most of these were pretty easy, and the
changes required are relatively minimal.
Some of the stuff left is harder. Pretty much everything under
`Metrics/*` is going to be a pretty big yak shave. A few of the others
are just going to need a little more work (e.g. `Style/ClassVars` and
`Style/GuardClause`). Going to stop here for now.
r? @ob-stripe
> Fix low hanging Rubocop TODOs

- .travis.yml
- test/stripe/product_test.rb
The upgrade broke a product related test that is now fixed.
r? @ob-stripe
> Upgrade to stripe-mock 0.8.0

- .rubocop_todo.yml
- lib/stripe.rb
- lib/stripe/usage_record.rb
- lib/stripe/util.rb
- test/stripe/plan_test.rb
- test/stripe/usage_record_test.rb
Implement support for flexible billing options on plans and creating usage records.
> Flexible/Metered Billing API support

- .travis.yml
- test/test_helper.rb
> Upgrade `stripe-mock` to v0.16.0

- README.md
I noticed that there's a minor spelling issue in the Readme, so I've made a small change. :)
> Readme: Fixed minor spelling issue.

- .travis.yml
- test/stripe/payment_intent_test.rb
> Move paymentintent to stripe-mock

- .travis.yml
- test/stripe/sigma/scheduled_query_run_test.rb
- test/stripe/source_transaction_test.rb
- test/test_helper.rb
> Move Scheduled Query Run and Source Transaction to stripe-mock

- .travis.yml
- lib/stripe.rb
- lib/stripe/subscription_item.rb
- lib/stripe/usage_record_summary.rb
- lib/stripe/util.rb
- test/stripe/usage_record_summary_test.rb
- test/test_helper.rb
> Add support for usage record summary

- lib/stripe/util.rb
Added in f0764594, unused since ede3625
> Remove unused Util.file_readable method

- .travis.yml
- lib/stripe.rb
- lib/stripe/account_link.rb
- lib/stripe/util.rb
- test/stripe/account_link_test.rb
- test/test_helper.rb
> Add support for the Account Link resource

- test/stripe_mock.rb
When starting a stripe-mock for a custom OpenAPI spec, pass `-http-port
0` on startup, which tells stripe-mock to select a port, then extract
that port from its output.
This is not a total win because we now have to rely on string matching,
but it is better in that (1) it gets a port more efficiently, (2) it
eliminates a race condition where another process could take the port we
found before stripe-mock gets to start, and (3) it starts a little
faster as we take advantage of the fact that we know stripe-mock has
started when we've found a port in its output (in my tests it took ~0.2
to 0.3 seconds compared to a 1 second sleep).
r? @ob-stripe Any feels on this? I was messing around with a Go script
and was thinking about taking an approach that looks a little more like
this one. I don't …
> Have stripe-mock select a port number

- .travis.yml
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
- test/test_helper.rb
> Fix tests to work on latest stripe-mock for future updates

- .travis.yml
- test/stripe/invoice_test.rb
- test/stripe/plan_test.rb
- test/test_helper.rb
> Fix our test suite for latest stripe-mock

- README.md
These options aren't immediately appartent without digging through the client source code. Might help future users!
> Readme: expanding fields and per-request API Version

- lib/stripe/topup.rb
Follow up to https://github.com/stripe/stripe-ruby/pull/773
We've missed a couple of diffs on our first pass.
r? @ob-stripe
> More method sorting for Topup class

- lib/stripe/bank_account.rb
- lib/stripe/card.rb
- lib/stripe/charge.rb
- lib/stripe/credit_note.rb
- lib/stripe/dispute.rb
- lib/stripe/invoice.rb
- lib/stripe/payment_method.rb
- lib/stripe/payout.rb
- lib/stripe/sku.rb
- lib/stripe/tax_id.rb
- lib/stripe/topup.rb
- lib/stripe/usage_record.rb
Hi again
These here are transformations from codegen that look relatively safe and not breaking. LMK if you want me to split the PR into more smaller ones with different types of transformations.
> Safe codegen transformations

- .editorconfig
- .vscode/extensions.json
- .vscode/settings.json
Adds configuration files for Visual Studio Code and EditorConfig.
> Add VSCode and EditorConfig files

- lib/stripe/object_types.rb
r? @ob-stripe 
cc @stripe/api-libraries @brandur-stripe 
Forgot it would be ~hard to elegantly put a comment there
> Some small changes to object_types for codegen

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
This is largely just another cleanup patch, but does a couple main
things:
* Hoists the `last_response` value into thread state. This is a very
minor nicety, but effectively makes `StripeClient` fully thread-safe,
which seems like a minor nicety. Two calls to `#request` to the same
`StripeObject` can now be executed on two different threads and their
results won't interfere with each other.
* Moves state off one-off `Thread.current` keys and into a single one
for the whole client which stores a new simple type of record called
`ThreadContext`. Again, this doesn't change much, but adds some minor
type safety and lets us document each field we expect to have in a
thread's context.
r? @ob-stripe
---
~~Note: targets the branch in #832 instead of `master`.~~
Note: …
> Do better bookkeeping when tracking state in `Thread.current`

- lib/stripe/resources/charge.rb
- lib/stripe/resources/subscription.rb
- test/stripe/subscription_test.rb
r? @ob-stripe (feel free to change reviewer)
> [codegen] Run codegen for stripe-ruby v5

- .travis.yml
- lib/stripe/resources/credit_note.rb
- test/stripe/credit_note_test.rb
- test/test_helper.rb
> Add support for CreditNote preview

- test/api_stub_helpers.rb
> Delete empty file

- lib/stripe/resources/checkout/session.rb
r? @remi-stripe 
Add support for listing Checkout sessions.
> Add support for listing Checkout sessions

- lib/stripe/resources/quote.rb
- test/stripe/quote_test.rb
Codegen for openapi 265b165.
r? @dcr-stripe
* Add support for `list_computed_upfront_line_items` method on resource `Quote`
> API Updates

- lib/stripe/object_types.rb
- lib/stripe/resources.rb
- lib/stripe/resources/application_fee_refund.rb
- lib/stripe/resources/bitcoin_transaction.rb
- lib/stripe/resources/capability.rb
- lib/stripe/resources/credit_note_line_item.rb
- lib/stripe/resources/customer_balance_transaction.rb
- lib/stripe/resources/invoice_line_item.rb
- lib/stripe/resources/line_item.rb
- lib/stripe/resources/login_link.rb
- lib/stripe/resources/person.rb
- lib/stripe/resources/reversal.rb
- lib/stripe/resources/tax_id.rb
- lib/stripe/resources/usage_record.rb
- lib/stripe/resources/usage_record_summary.rb
r? @stripe/api-library-reviewers 
No-op changes. Makes some missing files subject to codegen.
> Codegen more files

- .github/workflows/ci.yml
Confirmed that the script works. Enable automation on pushes to tags.
> Enable automated rubygems release

- lib/stripe/resources/customer.rb
- test/stripe/customer_test.rb
r? @kamil-stripe 
Update `retrieve_cash_balance` method to have a `params` argument.
> Update retrieve_cash_balance method to have params.

- .rubocop.yml
r? @anniel-stripe 
Remove stale Rubocop rules that are no longer needed.
> Refresh rubocop config.

- .github/workflows/ci.yml
Downloads started failing for the version we were using.
> Update jruby version

- lib/stripe/request_signing_authenticator.rb
- test/stripe/request_signing_authenticator_test.rb
- test/stripe/stripe_client_test.rb
Follow-up to https://github.com/stripe/stripe-ruby/pull/1212
> Request signing type checking and tests

- Gemfile
> Downgrade jaro_winkler

- README.md
Adapted from https://github.com/stripe/stripe-python/blob/beta/README.md#custom-requests
> Document raw_request

- lib/stripe.rb
- test/stripe_test.rb
Please +1 https://github.com/stripe/stripe-ruby/pull/1345/ as well!
> Add a helper to add a beta version

- README.md
Following https://github.com/stripe/stripe-ruby/pull/1343
> Update README to use add_beta_version

- .vscode/settings.json
- CHANGELOG.md
Fixes #1407
We need not have released version 11.5.0 of this SDK as there were no changes
> Add a note that 11.5.0 has no changes

- lib/stripe/resources/file.rb
Standardizing the way SDKs call files endpoint.
> Removed v1/files override

- README.md
- lib/stripe/api_requestor.rb
- lib/stripe/stripe_client.rb
- test/stripe/request_params_test.rb
> Merge changes from stripe-ruby/master

- README.md
Clean up after #1573
Remove unused link
> Remove unused youtube playlist link

- README.md
Add a note about the future of the legacy resource based pattern to the README
> Add legacy pattern deprecation plan to README

- .github/workflows/ci.yml
- .rubocop.yml
- README.md
- lib/stripe.rb
- lib/stripe/api_requestor.rb
- lib/stripe/request_options.rb
- lib/stripe/stripe_client.rb
- lib/stripe/stripe_configuration.rb
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- stripe.gemspec
- test/stripe/api_requestor_test.rb
- test/stripe/stripe_configuration_test.rb
- test/stripe/stripe_object_test.rb
- test/stripe_test.rb
* ran `just merge ruby-private-preview` from codegen folder
> Merge to private-preview

- examples/event_notification_webhook_handler.rb
I'm going back and sprucing up the new event notification handling examples. This will also go onto docs.stripe.com.
> Improve event notification example
