- lib/stripe/file_upload.rb
- lib/stripe/util.rb
- test/stripe/file_upload_test.rb
- test/test_data.rb
This allows the ruby bindings to be able to list all file upload objects.
r? @russelldavis (bindings maintainer)
> Adding support for listing file uploads.

- lib/stripe/util.rb
Fixes an issue where creating an `Account` did not return an `Account` instance.
> Add Account to business object mapping

- lib/stripe.rb
- lib/stripe/account.rb
- lib/stripe/api_operations/create.rb
- lib/stripe/api_operations/delete.rb
- lib/stripe/api_operations/list.rb
- lib/stripe/api_operations/request.rb
- lib/stripe/api_operations/update.rb
- lib/stripe/api_resource.rb
- lib/stripe/application_fee.rb
- lib/stripe/card.rb
- lib/stripe/charge.rb
- lib/stripe/customer.rb
- lib/stripe/file_upload.rb
- lib/stripe/invoice.rb
- lib/stripe/list_object.rb
- lib/stripe/stripe_object.rb
- lib/stripe/subscription.rb
- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
- test/stripe/stripe_object_test.rb
- test/stripe/util_test.rb
r? @russelldavis 
This will break existing uses of `Stripe::Account.retrieve(api_key)` (which now need the first param to be `nil`), but that seems like a minimally problematic change.
> Support persisted use of Stripe-Account header everywhere

- lib/stripe/account.rb
- lib/stripe/api_resource.rb
- lib/stripe/singleton_api_resource.rb
- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
- test/stripe/util_test.rb
I couldn't stomach the merge conflicts in https://github.com/stripe/stripe-ruby/pull/220 (I was working with an old fork).
An issue I've seen crop up is that if a global key is set (which most of your docs use), and then client API keys are used (eg. if using OAuth), then unexpected results can happen. This includes loading customer data from the parent global key.
```ruby
> require 'stripe'
> Stripe.api_key = "sk_test_foo"
=> "sk_test_foo"
> Stripe::Customer.all
> Stripe::Customer.all({}, { api_key: nil })
```
With my changes:
```ruby
> Stripe::Customer.all({}, { api_key: nil })
TypeError: api_key must be a String
```
I've also added `normalize_opts` usage to a bunch of places. I'm sure not all of these are necessary. I've added tests for the static `self.foo` ones. It is a slight flaw I …
> Safer argument parsing (attempt 2)

- lib/stripe/stripe_object.rb
In the API documentation it says you can replace an existing customer's credit card like this:
```ruby
cu = Stripe::Customer.retrieve({CUSTOMER_ID})
cu.source = {
'object' => 'card',
'number' => '424242424242',
..
}
cu.save
```
https://stripe.com/docs/api/ruby#update_customer
When you do this via the Stripe gem it will raise this error:
```
NoMethodError: undefined method `keys' for nil:NilClass
from ~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/stripe-1.20.4/lib/stripe/stripe_object.rb:136:in `serialize_nested_object'
from ~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/stripe-1.20.4/lib/stripe/stripe_object.rb:161:in `block in serialize_params'
from ~/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/stripe-1.20.4/lib/stripe/stripe_object.rb:159:in `each'
from …
```
> Dont unset keys when they dont exist

- lib/stripe.rb
Instead of shelling out to `uname`, use `/proc/version` when available.
On windows platforms, shell out to `ver` to report the OS version. On BSD and solaris platforms, also use `uname`.
And modify the checks to work on jruby, which reports a `RUBY_PLATFORM` of `java`.
> Revamp uname calls

- lib/stripe/card.rb
- test/stripe/customer_card_test.rb
* This error message said "Cards cannot be retrieved without a customer
ID. Retrieve a card using customer.cards.retrieve('card_id')"
This is incorrect. `customer.cards` throws a `NoMethodError: undefined
method `cards' for #<Stripe::Customer:0x0000010c8bdca8>`.
* The correct method is `Stripe::Customer#sources`, and this fixes the
error message.
> Fix incorrect error message- Stripe::Card.retrieve

- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
- test/stripe/application_fee_refund_test.rb
- test/stripe/application_fee_test.rb
- test/stripe/balance_test.rb
- test/stripe/bitcoin_receiver_test.rb
- test/stripe/charge_test.rb
- test/stripe/coupon_test.rb
- test/stripe/customer_card_test.rb
- test/stripe/customer_test.rb
- test/stripe/file_upload_test.rb
- test/stripe/invoice_test.rb
- test/stripe/list_object_test.rb
- test/stripe/metadata_test.rb
- test/stripe/recipient_card_test.rb
- test/stripe/refund_test.rb
- test/stripe/reversal_test.rb
- test/stripe/subscription_test.rb
- test/stripe/transfer_test.rb
- test/test_data.rb
Since the test data methods were prefixed with `test_` and being mixed into the UnitTest case, RakeTest was calling them as if they were unit tests. No more!
> Rename test data methods

- lib/stripe.rb
- lib/stripe/errors/card_error.rb
- lib/stripe/errors/invalid_request_error.rb
- lib/stripe/errors/stripe_error.rb
- test/test_data.rb
Now that [request IDs](https://stripe.com/docs/api#request_ids) are out, add them to all Stripe exceptions. Exception message will now also include the request ID, e.g. `(Status 404) (Request req_6XGwmgBn5LoBGM) No such customer: foo`
> Add request IDs to all API errors

- lib/stripe/util.rb
The issue in #266 occurs because the "token" object isn't mapped to a class. This pull request fixes that.
> Fix #266: Add Token to object classes map

- lib/stripe.rb
- test/stripe/api_resource_test.rb
> Handle error responses that are not hashes more gracefully

- lib/stripe/bitcoin_transaction.rb
- test/stripe/bitcoin_transaction_test.rb
Corrects the paths at which the client looks for Bitcoin transactions
and adds a small test suite to check these results.
Fixes stripe/stripe-ruby#236.
/cc @kyleconroy
> Correct list + retrieval of Bitcoin transactions

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
I am trying to store stripe object into database using `to_hash`, realizing that it's not handling arrays properly.
Thanks for adding this.
> to_hash should also walk into arrays to make recursive call.

- lib/stripe/util.rb
But we still want to percent-encode entities like spaces, so instead of
using `CGI.escape` we use a utility from WEBrick.
Fixes #286.
> Remove use of deprecated `URI.escape`

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
When constructing an object using .construct_from treat keys that are
strings the same as keys which are symbols by calling Util's
symbolize_names on an input hash. This makes guarantees around
consistency a little better.
Fixes #151.
> Perform deep name symbolization from .construct_from

- README.rdoc
Granular running of tests is one of Minitest's many gotchas. This
change adds some more information on how to run individual test suites
and individual tests which is useful when debugging.
> Add information on running individual test suites and individual tests

- lib/stripe/list_object.rb
- test/stripe/list_object_test.rb
This pulls the `Enumerable` mixin into `ListObject`. There is some
question in pulls like #167 as to the future of `ListObject` and how it
might change when pagination is introduced, but because we're unlikely
to make any backward incompatible changes to the API, it's likely that
`ListObject` will continue to represent a page of data that's been
extracted from the API. Given that assumption, pulling `Enumerable` in
should be relatively safe.
Fixes #227.
> Mix `Enumerable` into `ListObject`

- lib/stripe/stripe_object.rb
Problem
We broke API compatibility when we changed the interface for `initialize` from taking `api_key` as the second arg to an opts hash. If someone attempts to upgrade, calls from subclasses of StripeObject will  throw a `NoMethodError: merge` and log the api key in the process (it's not the expected hash)
Solution
For object initialization and refresh_from, call `normalize_opts` so `@opts` is always the expected hash.
cc @kyleconroy
> StripeObject: use Util.normalize_opts

- lib/stripe/list_object.rb
- test/stripe/list_object_test.rb
This makes ListObject behave a little more like an Array in that it gets
an #empty? helper. This should fit pretty well with the Enumerable
methods that it already has.
Replaces #193.
> Add #empty? helper on ListObject

- .travis.yml
I personally find that just looking at the red/green status of any given
pull request is enough information on the status of current builds.
@kyleconroy Thoughts on this change? Thanks!
> Don't give build notifications via e-mail

- lib/stripe/api_operations/update.rb
- test/stripe/api_resource_test.rb
Modifies the behavior of an update so that it can create an object if it
was new. This allows an "upsert"-like functionality where the SDK will
tend to do the right/expected thing.
This is a tad janky in that it checks for the existence of a class-level
`.create` method which is expected to come from a different module, but
most modules in the project are already fairly deeply intertwined and
co-dependent.
Fixes #165.
/cc @kyleconroy Mind taking a look at this one when you get a chance?
> Create if #save is called on a new object

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
This patch adds question marks helpers (e.g. #paid?) for any values in a
StripeObject that are a boolean. This is fairly idiomatic Ruby in that
it behaves similarly to other libraries like ActiveRecord.
Note that a caveat here is that nullable booleans will not get a helper
added for them if their current value is null. For this reason, we
should eventually prefer to derive these methods from some sort of
programmatic API manifest.
Replaces #257 and #274.
/cc @kyleconroy Mind taking a look at this one when you get a chance? I think
the code will work okay, but the caveat is fairly sizable. We could potentially
work around it though by trying to squash and outstanding nullable booleans
that we find in the API. Thanks!
> Add question mark helpers (e.g. #paid?) for boolean object values

- lib/stripe/api_operations/update.rb
- lib/stripe/stripe_object.rb
- test/stripe/api_resource_test.rb
- test/stripe/stripe_object_test.rb
As detailed in issue #119, we've somewhat unfortunately been allowing
object attributes to be passed in during a #save because we mix any
arguments directly into the serialized hash (it seems that this was
originally intended to be used more for meta parameters that go to the
request).
As also noted in #119, this use causes problems when certain types of
parameters (like subobjects) are used. We're now left in the somewhat
awkward position of either:
1. Removing this functionality on #save and breaking what may be
behavior that people depend on.
2. Fully support this mass assignment.
This patch takes the second path by extracting a new #update_attributes
method and using it from #save. It's still far from a perfect approach
because keys that have the same name as certain options (e.g. …
> Add attribute mass assignment and use it in #save

- lib/stripe/file_upload.rb
- test/stripe/file_upload_test.rb
Supersedes https://github.com/stripe/stripe-ruby/pull/312
r? @brandur cc @andrewpthorp
> Use correct URL for file upload retrieval

- lib/stripe/account.rb
- lib/stripe/api_operations/create.rb
- lib/stripe/bitcoin_receiver.rb
- lib/stripe/charge.rb
- lib/stripe/coupon.rb
- lib/stripe/customer.rb
- lib/stripe/dispute.rb
- lib/stripe/file_upload.rb
- lib/stripe/invoice.rb
- lib/stripe/invoice_item.rb
- lib/stripe/order.rb
- lib/stripe/plan.rb
- lib/stripe/product.rb
- lib/stripe/recipient.rb
- lib/stripe/refund.rb
- lib/stripe/sku.rb
- lib/stripe/token.rb
- lib/stripe/transfer.rb
Lets not be too shy about just using `extend` instead of `include` here
when it's more appropriate to do so. The advantage to this approach is
that the module can be either extended _or_ included with this change,
but couldn't be without it due to the `ClassMethods` meta-magic.
List has already started doing this as of #314, so we don't have to be
afraid of breaking convention here.
> Extend Stripe::APIOperations::Create instead of including

- lib/stripe/util.rb
Reverts stripe/stripe-ruby#299 due to the problem described in #318.
A more permanent fix hopefully exists in #319, but is a little bogged down with some problems with very old Ruby versions.
> Revert removal of `URI.escape`

- lib/stripe.rb
- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/metadata_test.rb
- test/stripe/util_test.rb
Pulls the test suite out of #319 so that we can get some coverage around
parameter encoding. This should prevent any recurrence of #318.
Also includes a little bit of refactoring.
> Add regression suite for testing parameter encoding

- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
- test/stripe/util_test.rb
Replaces my original attempt in #319 in a way that doesn't depend on `URI.encode_www_form` which doesn't exist in 1.8.7. This should hopefully get us the best of all worlds.
Caveats around use of `+` instead of `%20` as detailed in #319 still apply. @zenazn, If you have any insights into whether that might be a problem for our stack, please let me know. Thanks!
Fixes #286.
> Replace deprecated `URI.escape` with a customized `CGI.escape`

- lib/stripe/api_operations/update.rb
- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
This dials down the safety of `StripeObject`'s `#update_attributes`
method so that it allows properties to be assigned that it doesn't yet
know about. We're doing this for a few reasons:
1. To reflect the current behavior of accessors (i.e. `obj.name = ...`)
through `method_missing`.
2. To allow `#update_attributes` to assign properties on new objects
that don't yet know their schema from an API call.
Fixes #324.
> Have StripeObject#update_attributes reflect behavior of accessors

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Adds a special helper to `StripeObject` that helps a developer to
determine whether or not an object is deleted.
As described originally in #257, this is a bit of a special case because
a non-deleted object does not respond with `deleted` as part of its
representation, so while a deleted object would have this accessor
available automatically, non-deleted objects would not. This made use of
the SDK awkward because the presence of the method was not guaranteed.
Fixes #257 (again, heh).
/cc @kyleconroy @iloveitaly
> Add `StripeObject#deleted?`

- lib/stripe/api_operations/list.rb
- lib/stripe/list_object.rb
- test/stripe/list_object_test.rb
When additional filters were provided for pagination like an expansion
or a predicate, they would not propagate to any call after the first.
This patch addresses that issue by storing all filters and moving them
to any new page objects being created.
Fixes #331.
> Pass through all paging filters to descendent pages

- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/list_object_test.rb
- test/stripe/metadata_test.rb
- test/stripe/util_test.rb
I added this for a regression suite so that 1.8.7 could pass its tests,
but unfortunately this caused a regression in the way that parameters
are encoded for arrays of hashes. This patch reverts the change and adds
tests to detect a future regression.
(And 1.8.7 is expected to fail on this initial commit.)
> Remove sorting hack from parameter encoding

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Unfortunately usage of `#update_attributes` had rolled over from a time
where `#update_attributes_with_options` was still in use and `opts` were
being passed in as an optional argument which had the result of further
nesting the hash internally (i.e. `:opts => { :opts => ... } }`).
This patch fixes that problem, adds a regression test to prevent it from
reappearing, and banishes the unused `#update_attributes_with_options`.
Fixes #334.
> Correct internal usage of `#update_attributes`

- stripe.gemspec
I find myself using these quite a bit when looking into problems, and
currently have to manually re-add them to the Gemfile/gemspec to get
them in the bundle and make them available in tests.
Here we gate the debugger to only come in for Ruby > 2 so as to avoid
problems with various compatibility problems between debuggers and
versions of Ruby. If there's a demand for a pre-Ruby 2 debugger, we can
add that separately.
Any major objections to this one? Thanks.
> Add byebug/pry as a gem development dependency

- lib/stripe/account.rb
- lib/stripe/stripe_object.rb
- test/stripe/account_test.rb
- test/stripe/stripe_object_test.rb
- test/stripe/util_test.rb
We attempt to do a special encoding trick when serializing
`additional_owners` under an account: when updating a value, we actually
send the update parameters up as an integer-indexed hash rather than an
array. So instead of this:
field[]=item1&field[]=item2&field[]=item3
We send this:
field[0]=item1&field[1]=item2&field[2]=item3
The trouble is that this had previously been built into the core library
as the default handling for all arrays. Because of this, it was
impossible to resize a non-`additional_owners` array as described in
more detail in #340.
This patch special cases `additional_owners` and brings sane behavior
back to normal arrays along with a test suite so that we try to build
some better guarantees around both the general and non-general cases.
Fixes #340.
/cc @kyleconroy …
> Special case the serialization of account's `additional_owners`

- lib/stripe/bank_account.rb
- test/stripe/bank_account_test.rb
There aren't any tests for `Charge#capture` and other unique resource API calls, so I omitted tests with this PR.
> Adding BankAccount#verify

- test/stripe/list_object_test.rb
- test/stripe/util_test.rb
Pulls out a few pieces that were added specifically to support 1.8isms.
> Remove test hacks introduced to work around Ruby 1.8 limitations

- lib/stripe/application_fee.rb
- test/stripe/application_fee_test.rb
This uses the new endpoint instead of the deprecated one.
Related to stripe/stripe-php#208.
/cc @russelldavies It seems like you have a fair bit of context on this one.
Would you mind taking a look? Thanks!
> Correct URL used for refunding application fees

- README.rdoc
- lib/stripe.rb
- test/stripe/api_resource_test.rb
Retries can be turned on by setting
Stripe.max_retries_on_network_failure = 2 # or any other positive integer
Once the `max_retries_on_network_failure` is set to a positive integer, and request that fails on a network error will be retried.  There will be a sleep between each retry, the length of which is determined using an exponential backoff algorithm.
If a post request is made without an idempotency key and retries are on, then an idempotency key will be added automatically, since it is unsafe to retry without one.
`max_retry_sleep_seconds` is a float that can be set to configure that maximum time to sleep between retries (default is 2 seconds)
`base_retry_sleep_seconds` is a float can be set to configure the time to wait before the initial retry (default is 0.5 seconds)
> feat(request): optionally retry network failures

- lib/stripe/application_fee.rb
- test/stripe/application_fee_test.rb
Follows up the patch in #351, which I now believe is wrong. The trouble
is that we were mutating the application fee object, when in reality an
application fee refund is actually a completely new resource (see
[creating a refund][create-refund]). This patch edits the original
attempt to cut a new object and updates tests accordingly.
Once again, related to stripe/stripe-php#208.
CC @russelldavis Would you mind taking another look here? Thanks!
Also CC @remistr for general interest and additional sanity check.
Edit: Correct CC to Russell Davis (instead of Davies). Oops.
[create-refund]: https://stripe.com/docs/api#create_fee_refund
> Update application fee refunds (round 2)

- lib/stripe/bitcoin_receiver.rb
- test/test_data.rb
Stripe API responses include `customer: nil`, which caused `refresh` to throw an exception.
> BitcoinReceiver refresh fix

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
This is kind of a weird one because it'll only cause a failure when
serializing a subobject or hash of a `StripeObject`, but it's good
practice to initialize instance variables anyway.
Fixes #360.
> Always initialize `original_values` ivar in `StripeObject`

- lib/stripe/application_fee.rb
- lib/stripe/charge.rb
- test/stripe/api_resource_test.rb
- test/stripe/application_fee_test.rb
- test/stripe/charge_test.rb
As discussed previously in #354 and alluded to in #363, this patch
deprecates the `#refund` helpers on `Charge` and `ApplicationFee` in
favor of the resource-centric approach (i.e. `charge.refunds.create`).
We do this for a few reasons:
1. The new approach is far preferred and uses our modern endpoints. It's
also been the mechanism suggested by the documentation for ages now.
2. The old approach is somewhat risky in that a forgotten "s" can lead
to an accidental refund (i.e. `charge.refund` instead of
`charge.refunds`).
Follows up #354. Fixes #363.
Also reimplements `Charge#refund` to use our new refunds endpoint 
like we did in #354.
@kyleconroy @russelldavis If you guys have any thoughts on this one, I'd love
to hear them. Thanks!
> Deprecate `#refund` helpers on `Charge` and `ApplicationFee`

- README.rdoc
- lib/stripe.rb
- test/stripe_test.rb
As requested in #370, this will allow advanced users to configure a
certificate bundle that is expected to be more up-to-date than what
we've managed to include with the gem.
/cc @kyleconroy Would you mind taking a review pass on this one? Thanks!
> Allow the CA bundle to be configured

- .travis.yml
- README.rdoc
- gemfiles/json.gemfile
- stripe.gemspec
All required rubies include JSON as part of the stdlib.
See: https://github.com/rails/rails/pull/23453
> Remove json gem dependency

- README.md
This is kind of a bike shed, but at this point it's a little more clear
that Markdown has won the format wars and that people are a little more
used to seeing/editing it.
This moves the `README` to Markdown and also includes some minor
cleanup:
* Fixes a broken reference link (`curl`).
* Normalizes lines to 80 characters.
* Normalizes code snippets to be prefixed by four spaces.
* Normalizes sentences to be separately by only a single space.
> Change README to Markdown

- lib/stripe/application_fee.rb
`params` and `opts` are not currently passed through when using the
`#refund` helper on `ApplicationFee`. This was an omission on the
original refactor to use the new endpoint, and wasn't an intentional
design.
Fixes #386.
> Pass params and opts through on `ApplicationFee#refund`

- lib/stripe/stripe_object.rb
- test/stripe/api_resource_test.rb
- test/stripe/stripe_object_test.rb
Adds a basic fix for serialization of hashes passed to `#save`. Previously, these would produce non-sensical output that would be rejected by the API.
This fix is designed to help curb the pain of the current problem, but isn't 100%. Serialization will still be problematic for hashes that are found inside of an array.
Fixes #384.
/cc @francois2metz I pulled your patch in here. Thanks!
> Fix serialization of hashes passed to `#save`

- lib/stripe/account.rb
- lib/stripe/api_operations/update.rb
- lib/stripe/stripe_object.rb
- test/stripe/account_test.rb
- test/stripe/stripe_object_test.rb
This pull does two major things:
1. Refactors `serialize_params` to be more concise and readable while still complying to our existing test suite. Unfortunately over time this method has become a ball of mud that's very difficult to reason about, as recently evidenced by #384.
2. Moves `serialize_params` from class method to instance method (while still keeping for old class method for backwards compatibility). This is to give it a more sane interface.
The test suite around serialization is fairly comprehensive so we can be reasonably sure that this will work as expected; although it wouldn't be too surprising to find yet another edge case caused by `additional_owners`.
> Refactor `serialize_params` under `StripeObject`

- lib/stripe/list_object.rb
- test/stripe/list_object_test.rb
In #394 we renamed `url` to `resource_url` in order to prevent name
collisions in API resource that also have a `url` property.
Unfortunately, this didn't account for the fact that when making API
calls on a list object we rely on a returned `url` property to build a
request, and this had been renamed to `resource_url`. Tests should have
caught this, but they were written to work differently than how live
API calls actually function.
This patch repairs the problem by adding a `resource_url` to list
objects, and modifies test to be more accurate to reality so that
they'll catch this class of problem in the future.
Fixes #395.
> Fix reference to URLs on ListObject

- .travis.yml
- Gemfile
- gemfiles/default-with-activesupport.gemfile
- gemfiles/yajl.gemfile
- stripe.gemspec
Here we predicate the installation of Byebug on being on the MRI. This
allows us to `bundle install` on alternate platforms like JRuby.
> Lock Byebug to just the MRI

- lib/stripe.rb
Certain platforms will throw an error if this variable is accessed
without being initialized. Assign it a value instead of relying on the
OR operator to give it a default.
> Initialize @max_network_retries

- lib/stripe/account.rb
- test/stripe/account_test.rb
Adds bindings for the [Account.reject](https://stripe.com/docs/api#reject_account) method.
> Create account.reject method.

- lib/stripe/api_operations/update.rb
- test/stripe/api_resource_test.rb
in the same manner as is already possible for .create.
Use-case / rationale:
For some operations, we don't care whether we are operating on a new or an existing object. For example, we'd do something like the below upon receiving a new card token. We may receive a card token either because a user just entered her payment information for the first time, or because she wants to update existing information. We'd like to handle both cases in a single endpoint.
```ruby
class User
def stripe_customer
@stripe_customer ||=
if stripe_customer_id?
Stripe::Customer.retrieve(stripe_customer_id)
else
Stripe::Customer.new.tap { |sc| sc.update_attributes(email: email) }
end
end
def update_payment_info!(stripe_token)
stripe_customer.source = stripe_token
stripe_customer.save &&
self.stripe_customer_id …
```
> Allow options (headers) to be passed into .save

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
This improves the error message that a user sees when attempting to set
a property to an empty string.
> Improve error message on setting empty strings

- lib/stripe.rb
This attempts to give some semblance of thread safety to parallel
library requests by pre-assigning a certificate store, the
initialization of which seems to be a weak point for thread safety. Note
that while this does seem to empirically improve the situation, it
doesn't guarantee actual thread safety.
A longer term solution to the problem is probably to assign a per-thread
HTTP client for much stronger guarantees, but this is a little further
out. More discussion on that topic in #313.
Fixes #382.
> Initialize an internal CA store

- lib/stripe/stripe_object.rb
- test/stripe/api_resource_test.rb
- test/stripe/stripe_object_test.rb
Prior to my last major serialization refactor, there was a check in the
code that would remove any subobjects from serialization that were of
their own proper resource type (for example, if a charge contained a
customer, that customer would be removed).
What I didn't realize at the time is that the old serialization code had
a bug/quirk that would allow *certain types* of subobjects that were API
resources to make it through unscathed.
In short, the behavior requirement here is *directly* contradictory.
There was a test in place that would make sure that `customer` was
removed from this hash:
``` ruby
{
:id => 'ch_id',
:object => 'charge',
:customer => {
:object => 'customer',
:id => 'customer_id'
}
}
```
But, as reported in #406, we expect, and indeed need, for `source` (a
card) to make …
> Remove check that prevents API resource subobjects from being serialized

- lib/stripe.rb
- test/stripe/api_resource_test.rb
This is consistent with API library behavior in other languages, and with our API documentation (which doesn't mention needing to handle this type of error).
r? @brandur 
> Catch SSL connection errors, and re-raise them as APIConnectionErrors

- test/stripe/charge_test.rb
- test/test_data.rb
This PR adds a test to ensure that the forthcoming `outcome` nested subfield on the charge resource is rendered correctly by ruby bindings.
r? @brandur
> add test for handling of charge.outcome subfield

- lib/stripe/api_operations/list.rb
- lib/stripe/charge.rb
- lib/stripe/stripe_object.rb
- lib/stripe/subscription.rb
- lib/stripe/transfer.rb
- lib/stripe/util.rb
- test/stripe/api_resource_test.rb
- test/stripe/bitcoin_receiver_test.rb
- test/stripe/stripe_object_test.rb
- test/test_helper.rb
I'm not sure exactly what changed here (did we change the `$VERBOSE`
setting?), but I'm not seeing a whole lot of warnings when running the
test suites locally and in CI. For example:
```
Started
........................................./home/travis/build/stripe/stripe-ruby/lib/stripe/api_operations/list.rb:6: warning: instance variable @opts not initialized
............../home/travis/build/stripe/stripe-ruby/lib/stripe/api_operations/list.rb:6: warning: instance variable @opts not initialized
../home/travis/build/stripe/stripe-ruby/lib/stripe/api_operations/list.rb:6: warning: instance variable @opts not initialized
......../home/travis/build/stripe/stripe-ruby/lib/stripe/api_operations/list.rb:6: warning: instance variable @opts not initialized …
```
> Fix warnings emitted during tests

- lib/stripe.rb
- test/stripe_test.rb
- When performing requests on the behalf of a managed account, `stripe_account` option must be passed everytime, this can become redundant
- Allowing to set the `stripe_account` globally makes thing easier for wrapping every request in a single method, the same way as it is when defining the `api_key` globally
@matthelm
> Allow `stripe_account` to be set globally:

- lib/stripe/subscription.rb
- test/stripe/subscription_test.rb
- test/test_data.rb
This PR:
Changes the v1/cus/cus_123/sub/* style URL to v1/sub/* so the Ruby bindings call the new API endpoints
Allows subscriptions to be retrieved, created, and listed directly
Continues support for update and deletion of subs
Updates the tests to use the methodology of the new docs and call the new endpoint
Not merging until data has been backfilled since this uses the new v1/subs API endpoints which rely on Subs data model.
> Use v1/subs endpoints for operations on subs and allow direct sub access

- lib/stripe.rb
- lib/stripe/order.rb
- lib/stripe/order_return.rb
- lib/stripe/util.rb
- test/stripe/order_return_test.rb
- test/stripe/order_test.rb
- test/test_data.rb
r? @stripe/api-libraries
cc @jimdanz 
There's a sad naming conflict here around `return` and since `returns` is already a property on the order this seemed like the third best choice. Very happy to rename though if anyone has any suggestions!
> Add order returns

- lib/stripe/util.rb
Adds some basic documentation to `Util.convert_to_stripe_object`.
> Document `Util.convert_to_stripe_object`

- lib/stripe/order.rb
- test/stripe/order_test.rb
- test/test_data.rb
r? @stripe/api-libraries 
cc @jimdanz 
The object we get from `/v1/orders/:id/returns` is an `OrderReturn` and not an `Order`. We want to use `Util.convert_to_stripe_object` to deserialize instead of `initialize_from`.
> Convert return_order response to OrderReturn.

- lib/stripe/api_operations/update.rb
- This removes the doc about `req_url` while saving a StripeObject, this options was removed in https://github.com/stripe/stripe-ruby/commit/e226ef
> Removed a forgotten line of doc [ci skip]:

- Gemfile
- test/test_helper.rb
CI is failing for a number of Ruby versions because shoulda is pulling
in should-matchers, which then pulls in activesupport. activesupport's
new 5.0.0 version is being picked up, and that requires at least Ruby
2.2.2.
Luckily the solution is easy, we're not using shoulda-matchers, only
shoulda-context, so just tighten up our dependencies a little and the
problem goes away.
> Fix Gem builds in CI

- lib/stripe/api_resource.rb
- lib/stripe/customer.rb
- lib/stripe/stripe_object.rb
- test/stripe/api_resource_test.rb
- test/stripe/customer_test.rb
- test/stripe/stripe_object_test.rb
This one is a bit of a story, but to put this as succinctly as possible, this patch makes the following changes:
1. Reverts the behavior introduced #407. This means that subresources go back to not being serialized when a parent is saved by default.
2. Introduce a new flag on `APIResource` called `#save_with_parent` that allows this behavior to be overridden.
3. Apply behavior override to `Customer#source=`.
And now for some more detailed history: in #406 it was brought to my attention that a change had broken the ability to replace a source on a customer with a nnew card _object_ (note that this is a slightly unusual thing to do as you would normally want to replace it with a token):
``` ruby
customer = Customer.retrieve(...)
customer.source = {
object: 'card',
number: …
```
> Go back to not saving subresources, but exclude `Customer#source=`

- lib/stripe.rb
- test/stripe/api_resource_test.rb
Two changes:
1. The HTTP retry path has been refactored to make retries on errors
that are not RestClient exceptions possible by bringing the logic up a
level. This also has the effect of somewhat simplifying the exception
handling logic which can be somewhat difficult to reason about right
now.
2. Retry on `RestClient::Conflict` (a 409 from the API) as discussed in
issue #431.
Note that I also trimmed down the retry test cases a bit so as to replace some of the more verbose ones with simpler tests that are closer to the implementation (i.e. by testing `.should_retry?` instead of performing HTTP requests against a mock for every type of exception that we care about).
Fixes #431.
> Rework HTTP retry path + retry 409s

- lib/stripe.rb
This removes a hack in the code that's designed to work around a
rest-client bug which was added back in 2011. Unfortunately neither
comments nor commit messages bother to tell us what the nature of the
bug actually was, but based on what it's rescuing, it might be
rest-client/rest-client#58, which has been fixed for over five years
now.
Following up on the work done in #436, let's continue to try and simply
the error handling paths by taking this out.
> Remove hack to work around rest-client bug

- Gemfile
This locks development (which will run in Travis) onto an older version of rest-client and mime-types. mime-types in particular has recently become only compatible with Ruby >= 2, and we're still trying to support 1.9.3. This has caused problems when relaxing the allowed versions of rest-client as seen in #439.
The change won't affect production (a much wider spread of versions is allowed by the gemspec).
Unblocks #439.
> Workaround for mime-types related failures on 1.9

- stripe.gemspec
Hi!
rest-client version 2.0 was released last week: https://github.com/rest-client/rest-client/commit/3a79728b332d316afa281d10022658735a6f72df
Per the [upgrade notes](https://github.com/rest-client/rest-client/commit/3a79728b332d316afa281d10022658735a6f72df) and [history](https://github.com/rest-client/rest-client/blob/master/history.md#200), version 2.x is largely compatible API with version 1.x. I couldn't find this library using any deprecated features, tests passed for me locally (ruby 2.3.1), and I've been using this fork in production for about 24 hours without any problems so far.
Given this is the only dependency of the Stripe library, and the 2.x release of rest-client drops support for Ruby 1.9, I'd be happy to set up something like https://github.com/thoughtbot/appraisal to …
> Relax rest-client version requirements

- README.md
Add a section that contains basic usage information to the README. The API docs are still the canonical reference of course, but this may help avoid an extra jump.
Attemps to address some of the confusion raised in #261.
@olivierbellone @remistr Any thoughts on this one?
> Add usage section to README

- lib/stripe/util.rb
- test/stripe/account_test.rb
- test/stripe/util_test.rb
Alphabetizing maps being encoded by key can cause problems because the
server side Rack relies on the fact that that a new array item will
start with a repeated key.
For example, given this encoding:
``` ruby
items: [
{ :type => 'sku', :parent => 'sku_94ZYSC0wppRTbk' },
{ :type => 'discount', :amount => -10000, :currency => 'cad', :description => 'potato' }
],
```
We need to have `type` appear first so that an array boundary is
recognized. So the encoded form should take:
```
items[][type]=sku&items[][parent]=...&items[][type]=discount&items[][amount]=...
```
But currently `type` gets sorted to the back, so we get something more
like:
```
items[][parent]=...&items[][type]=...&items[][amount]=...&items[][currency]=...&items[][description]=...&items[][type]=potato
```
Which the server will …
> Don't alphabetize encoded maps by key

- lib/stripe/util.rb
- test/stripe/charge_test.rb
- test/stripe/util_test.rb
This produces an error when we detect an "array of maps" that cannot be
encoded with `application/x-www-form-urlencoded`; that is to say, one
that does not have each hash starting with a consistent key that will
allow a Rack-compliant server to recognize boundaries.
So for example, this is fine:
```
items: [
{ :type => 'sku', :parent => 'sku_94ZYSC0wppRTbk' },
{ :type => 'discount', :amount => -10000, :currency => 'cad', :description => 'potato' }
],
```
But this is _not_ okay:
```
items: [
{ :type => 'sku', :parent => 'sku_94ZYSC0wppRTbk' },
{ :amount => -10000, :currency => 'cad', :description => 'potato', :type => 'discount' }
],
```
(`type` should be moved to the beginning of the array.)
The purpose of this change is to give users better feedback when they
run into an encoding problem …
> Produce an error on bad array of maps

- lib/stripe.rb
- test/stripe/api_resource_test.rb
- test/stripe/invoice_test.rb
- test/stripe_test.rb
This moves away from rest-client's convention of using symbols as header
names so as to present less obfuscation as to how these are actually
named when they go over the wire.
Because headers can be injected via the bindings' API I was initially
worried that this change might break something, but upon inspection of
rest-client source, I can see now that headers take precedence as
assigned by their insertion order into the header hash, and are
"stringified" in that same loop [1]. This means that even if a user
injects a symbolized header name (`:idempotency_key`), it will still
correctly overwrite the one generated by stripe-ruby despite that using
the string format (`"Idempotency-Key"`).
r? @dpetrovics Mind taking a pass on this one too? Thanks!
[1] …
> Move away from rest-client's "symbol header names"

- lib/stripe/account.rb
- test/stripe/account_test.rb
In #433, we built a framework under which subresources are usually not
persisted, but in certain cases they can be. At the time,
`Customer#source` was the only field that I knew about that had to be
flagged into it.
Issue #456 has raised that we also be doing `Account#external_account`.
This patch adds support for that.
Fixes #456.
r? @guillaumehenriot Does this look right to you? Thanks!
> Flag Account#external_account into save_with_parent system

- lib/stripe/account.rb
- lib/stripe/api_resource.rb
- lib/stripe/customer.rb
- lib/stripe/subscription.rb
- test/stripe/account_test.rb
- test/stripe/api_resource_test.rb
Since #433, saving API resources nested under other API resources has
not been the default. Instead, any instances where this should occur
have been special cased with specific method implementations that would
set the `#save_with_parent` flag when a field is written.
This ended up causing some problems because as seen in #457, because
places that we need to do this aren't well vetted, some were forgotten.
This makes implementation of new fields that need this behavior simpler
by implementing a `.save_nested_resource` metraprogramming method on the
`APIResource` class. This can be called as necessary by any concrete API
resource implementations.
We replace existing implementatinos and also add one to `Subscription`,
which had previously been suffering from a similar problem where its …
> Generalize saving nested resources

- test/stripe/api_resource_test.rb
- test/stripe/subscription_test.rb
These aren't causing the build to fail or anything, but they do get
spewed out every time our test suite runs.
> Fix interpreter warnings

- Gemfile
- stripe.gemspec
Our fairly old requirements for rest-client (and therefore mime-types)
are starting to cause some dependency hell problems for some customers.
Try relaxing these constraints and locking 1.9 specifically into
compatible versions.
Fixes #459.
> Relax rest-client requirements

- lib/stripe.rb
- lib/stripe/apple_pay_domain.rb
- lib/stripe/util.rb
- test/stripe/apple_pay_domain_test.rb
- test/test_data.rb
Allows you to create a `Stripe::ApplePay::Domain` in Ruby
> Ruby bindings for ApplePayDomain

- README.md
Previously it was wrongly saying about `GET` requests.
Vide https://github.com/stripe/stripe-ruby/blob/c131bcbcacc71ea9c8e331421b22f8ef3423e0e1/lib/stripe.rb#L327
[ci skip]
> Fixed description about DELETE request retries

- lib/stripe.rb
- lib/stripe/errors/permission_error.rb
- lib/stripe/errors/permissions_error.rb
- test/stripe/api_resource_test.rb
The addition of this class was unreleased so this is not a breaking
change.
> Rename error class to be singular "permissions"

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
I tried upgrading the Stripe bindings and ran into an issue. Our code is doing this when it's trying to update the bank account information:
```ruby
response = Stripe::Account.new(account_token).save(request_params)
```
where request_params includes a bank_account: `btok_1234` entry. This is currently in production and works fine, but after we update the Ruby bindings, we get this error:
```ruby
NameError: method `bank_account=' not defined in #<Class:0x007f84d2c6b890>
```
We investigated and tracked it down to the Ruby bindings. It seems like Stripe::StripeObject#update_attributes should look something like this:
```ruby
def update_attributes(values, opts = {}, method_options = {})
dirty = method_options.fetch(:dirty, true)
values.each do |k, v|
add_accessors([k], values) unless …
```
> Create accessor methods in update_attributes

- lib/stripe/stripe_object.rb
I remove `respond_to?` method because stripe-ruby requires Ruby 1.9.3 or above.
Thank you.
> Remove respond_to? method for Ruby 1.9.2 or earlier

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
When using the `to_s` method to print out the values it now prints the embedded objects as a string, which makes it look bad.
The solution I'm proposing is to use a copy object that will contain a hash for all values. It will use `to_hash` for any embedded stripe objects.
This should allow us to print all of the StripeObjects within a stripe object.
This may not be exactly right, but the test if nothing else should show the issue.
@brandur
> Allow to_s to also pretty_generate embedded StripeObjects

- lib/stripe/account.rb
- lib/stripe/api_operations/save.rb
- lib/stripe/stripe_object.rb
- test/stripe/account_test.rb
- test/stripe/api_operations_test.rb
As described in #481, adding a protected field like `legal_entity` as
part of an update API operation can cause some issues like a custom
encoding scheme not being considered and special handling around empty
values being ignored.
As a an easy fix for this, let's disallow access to protected fields in
the same way that we disallow them from being set directly on an
instance of a given model.
Helps address (but is not a complete fix for) #481.
r? @grey-stripe Would you mind taking a review pass on this one?
> Don't allow protected fields in `Save.update` API operation

- test/stripe/errors_test.rb
Just adds a super simplistic test for the errors module. The win here is
to (hopefully) lower the friction a little bit the next time a feature
is introduced into errors because there's now suite where a new test can
be written.
Follows up #487 through #489 as very minor improvements.
> Add basic test for errors

- lib/stripe.rb
- test/stripe_test.rb
Colocates the helper methods for looking up a uname by renaming them to
have the same prefix as the base method (i.e. `get_uname`).
Also adds an additional rescue in case we try to run an executable on a
system but it wasn't founded (this should never happen).
Also adds some tests to make sure that each method gets at least a very
basic amount of exercise in the test suite.
Follows up minor improvements in #487 through #490.
> Colocate uname helpers + tests

- lib/stripe/source.rb
- test/stripe/source_test.rb
- test/test_data.rb
r? @brandur-stripe
cc @stripe/api-libraries @will-stripe
This PR:
- disables the "list" method for sources (the API does not support it)
- adds a bunch of tests for sources
> Better tests for sources

- .travis.yml
- Gemfile
- README.md
This has been discussed, but we'll finally be doing it for the next
major version so that we can introduce a few features that depend on
gems that don't support 1.9.
> Remove support for Ruby 1.9

- lib/stripe/file_upload.rb
- lib/stripe/stripe_client.rb
- test/stripe/file_upload_test.rb
As described in #506, file uploads were broken on the way over to
Faraday and unfortunately I didn't catch it because the file upload
creation test wasn't using a matcher that was strict enough to really
catch anything.
Here we add the multipart middleware to our Faraday connection, add a
compatibility layer to `FileUpload` so that we can support `File` like
the rest-client based version always did (Faraday generally expects an
`UploadIO` object), and then tighten up our tests so that we'd be able
to catch future regressions.
Fixes #506.
r? @ob-stripe Mind taking a look at this one? Thanks!
> Properly encode file uploads

- spec/fixtures.json
- spec/fixtures.yaml
- spec/spec.json
- spec/spec.yaml
- test/stripe/recipient_card_test.rb
Uses our latest generated OpenAPI spec.
We end up having to change the expected resource on a few tests because bank accounts and cards were recently consolidated into a single resource internally and this led to some synthesized responses becoming a little more accurate.
> Bump OpenAPI spec to latest

- README.md
Minor difference in vernacular, but as noted in stripe/stripe-node#312, the usage of the word "bindings" is unusual outside of Stripe.
[The new rendered README](https://github.com/stripe/stripe-ruby/blob/brandur-readme-update/README.md).
r? @romain-stripe
> Prefer use of the word "library" over "bindings"

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
The Faraday::Response object does not respond to #code. The correct message is #status. It seems this case was previously unhandled by the test suite as there was no case for the server responding "success" with an invalid JSON body.
Before the fix, the new test fails with:
```
» be rake
/Users/jay/.gem/ruby/2.4.0/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:400: warning: assigned but unused variable -context
Loaded suite /Users/jay/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader
Started
..................................................................................................................................
............................................................................F …
```
> Replace invalid message Faraday::Response#code with valid #status

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Fixes #512. The fix is not very elegant and somewhat brittle (what if we add other unmarshallable objects to `@opts`?) but it does the job. If you have a better suggestion for handling this, I'm happy to update the PR or close it in favor of a better solution.
> Exclude client when dumping objects

- lib/stripe/card.rb
- lib/stripe/source.rb
- lib/stripe/util.rb
- openapi/fixtures.json
- openapi/fixtures.yaml
- test/stripe/customer_card_test.rb
- test/stripe/source_test.rb
cc @stripe/api-libraries @will-stripe
This PR adds support for detaching sources from customers. Unlike cards or bank accounts, sources cannot be deleted, but they can now be detached from customers by sending a `DELETE` request to `/v1/customers/{CUSTOMER_ID}/sources/{SOURCE_ID}`.
Incidentally, while working on this PR, I stumbled upon a couple of related issues:
- we were lacking an entry for `source` in  [`Util.object_classes`](https://github.com/stripe/stripe-ruby/blob/5dd5d2b608af8b597b5298b22eab171d570d6408/lib/stripe/util.rb#L20). This means that `source` objects returned by the API were instantiated as generic `StripeObject`s rather than `Source`s
- the `source` entry in `fixtures.json` currently contains a card object rather than a source object
I've fixed the …
> Adds support for detaching sources from customers

- Rakefile
- openapi/fixtures.json
- openapi/fixtures.yaml
- openapi/spec2.json
- openapi/spec2.yaml
- test/api_fixtures.rb
- test/api_stub_helpers.rb
See [1] for details, but a few conventions changed around the structure
of the OpenAPI repository and the data within the fixtures file. Here we
put in some minor changes to compensate for them.
[1] https://github.com/stripe/openapi/pull/3
> Update some OpenAPI repository conventions

- stripe.gemspec
Fixes #526 
The [`SSLOptions`](https://github.com/lostisland/faraday/blob/v0.9.0/lib/faraday/options.rb#L204) class was introduced in v0.9.0, so I set it as the minimum required version.
> Fix Faraday minimum version

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Previously, the value of whatever accessor was missing was left out of the call to build it. This had the effect of skipping over the lazily-built predicate method when the missing accessor is for a boolean.
Of course, I realize this all is a bit contrived as most of the time folks aren't assigning these values manually to stripe objects. However, in my testing it caught me by surprised that the behavior is asymmetric depending on how and when values are assigned.
As such I believe this is a less surprising implementation.
I wasn't sure how best to design the test, so I'm happy to move things around in order to closer follow the projects conventions.
Thank you for your care of a tremendously useful library! ❤️
> Include predicate for lazily added boolean accessors

- README.md
- lib/stripe.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
- test/stripe_test.rb
Adds support for "app info" (a mechanism that allows a plugin's author to identify that plugin) in Ruby. This is already supported in PHP and we're adding it elsewhere.
r? @ob-stripe One thing I didn't do here is add the app info the user agent string (like PHP does). I figure this is okay since we're mostly using the JSON version in the backend anyway. Thoughts?
> Support "app info" for plugins in Ruby

- lib/stripe/util.rb
I'm using this utility function to convert `StripeObject`s into their more specific concrete type (like `Stripe::Card`). For me, it's always the case that `opts` is `{}`, so for me at least, it'd be helpful if this was the default value so one doesn't need to specify it everywhere.
> Don't require `opts` param for `convert_to_stripe_object`.

- README.md
Timeouts are about to come to stripe-java [1], so for consistency we
mirror the README section that we're going to be adding over there.
[1] https://github.com/stripe/stripe-java/pull/369
r? @ob-stripe
> Add section for configuring timeouts to README

- lib/stripe.rb
- lib/stripe/errors.rb
- lib/stripe/util.rb
- lib/stripe/webhook.rb
- test/stripe/webhook_test.rb
> Support for deserializing webhook events and verifying signatures

- lib/stripe.rb
- lib/stripe/account.rb
- lib/stripe/errors.rb
- lib/stripe/oauth.rb
- lib/stripe/stripe_client.rb
- test/stripe/oauth_test.rb
- test/stripe/stripe_client_test.rb
This PR adds support for Connect's OAuth flow directly in the library.
I took a similar approach to https://github.com/stripe/stripe-python/pull/287 and subclassed `StripeClient` to correctly handle errors returned by `connect.stripe.com`.
wdyt?
> Add OAuth methods

- lib/stripe/api_operations/request.rb
- test/stripe/api_resource_test.rb
Fixes #544. Also add a test case to ensure that there's a warning in stderr when `idempotency_key` is in the `params` hash, and not in the `opts` hash.
> Warn if idempotency_key is in params hash

- README.md
There's a small error in the docs. The last response is returned as the second return value of `Stripe::StripeClient#request`.
> Fix documentation for getting a request id

- test/stripe/ephemeral_key_test.rb
Redefining the constant like this produces a warning:
```
$ bundle exec rake
/Users/brandur/stripe/stripe-ruby/test/stripe/ephemeral_key_test.rb:75: warning: already initialized constant Stripe::EphemeralKeyTest::FIXTURE
/Users/brandur/stripe/stripe-ruby/test/stripe/ephemeral_key_test.rb:6: warning: previous definition of FIXTURE was here
Loaded suite /Users/brandur/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader
Started
...
```
They also don't appear to be used, so it should be fine just to strip
them out of the test suite.
r? @grey-stripe
> Remove `FIXTURE` definitions for ephemeral keys

- lib/stripe/invoice.rb
- test/stripe/invoice_test.rb
r? @brandur-stripe
cc @stripe/api-libraries @ark-stripe
Users can now provide a `source` parameter when paying invoices, but the `pay` method currently does not let users provide any parameters. This PR fixes that.
Unfortunately, this is a breaking change because if someone is currently passing a `opts` argument, they'll need to modify their code since it's now the second argument. I didn't want to add `params` as the second argument since it would be inconsistent with ~every other method in the library.
> Add parameters when calling `pay` on an invoice

- lib/stripe/account.rb
- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Tweaks the serialization behavior so that when a resource is explicitly set
to a resource's field and that resource is subsequently saved, then if it
looks like the set resource was persisted we extract its ID and send it up
to the API.
By slight extension we also throw an `ArgumentError` if it looks like that
set resource was _not_ persisted because if the user set it explicitly then
it was probably not their intention to have it silently ignored by the
library in the event of a problem.
Fixes #558.
> Include IDs of resources set into properties

- lib/stripe/errors.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
The OAuth deauthorization endpoint can return an `invalid_client` error code, but the ruby API client doesn't expect it. That means it goes through `specific_oauth_error`, ends with `nil`, and then goes to `specific_api_error`, and then raises a `TypeError`.
This accepts and handles the `invalid_client` error code with a new error class.
For a general fix, probably nothing should go to `specific_api_error` after `specific_oauth_error` is attempted, since getting the oauth error is only tried when the error data is a string, and the api error expects the error data to be a hash. That's just asking for trouble.
(@sandrasi found this, and I decided to make the PR for it)
> handle invalid-client oauth error

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
It was brought up in #562 that in case we receive an OAuth error that we
don't know about, `specific_oauth_error` will fall through with a `nil`,
then picked up by `specific_api_error` which will always try to handle
the error as if it were a `Hash` (even if we know it's not!) and thus
lead to typing problems at runtime.
This patch throws a generic `OAuthError` in cases where a code comes
back that we don't recognize. I'm still crazy about the fact that we
don't have a better way of recognizing an OAuth error in particular, but
it should do the trick.
r? @ob-stripe
> Improve error handling safety in the event of unrecognized OAuth error

- lib/stripe/stripe_client.rb
- test/stripe/invoice_test.rb
- test/stripe/stripe_client_test.rb
Currently, with a normal API resource, you can unset fields by
specifying a `nil` to that field's setter:
``` ruby
c = Charge.retrieve('ch_123')
c.customer = nil
c.save
```
This actually gets serialized as the form `customer=` (i.e. an empty
string), but we had to use the empty string to handle unsets because
form encoding has no concept of a `nil`/`null`.
To try and prevent usage errors, we actually prevent you from setting
fields with an empty string:
``` ruby
c = Charge.retrieve('ch_123')
c.customer = '' # error! use nil instead
```
When specifying parameters though, this doesn't work anywhere nearly as
well because usage patterns like this are very common in Ruby:
``` ruby
charge_opts = {
params[:amount],
params[:currency],
params[:customer],
}
charge = Charge.create(charge_opts)
``` …
> Allow empty strings in API invocation parameters

- test/stripe/invoice_test.rb
Since this commit: https://github.com/stripe/stripe-ruby/commit/0019cfdc7e44f18503d5cf16e9bb9b1ad31065d4#diff-392254e7a00123f08e60cb565776b883L47 removed the test for passing in subscription items to upcoming invoice, I am adding another test for passing in a list of subscription items into upcoming invoices endpoint.
> Add upcoming invoice subscription items test

- Gemfile
- README.md
- lib/stripe.rb
- lib/stripe/stripe_client.rb
- lib/stripe/util.rb
- test/stripe/stripe_client_test.rb
- test/stripe/util_test.rb
- test/test_helper.rb
Adds logging support for stripe-ruby in a similar way that we did it for stripe-python [1], with the idea that users you can optionally get some additional low-cost-to-configure logging for operational visibility or debugging.
I made a few tweaks from the Python implementation (which I'll try to contribute back to there):
* Added an `elapsed` parameter to responses so you can tell how long they lasted.
* Mixed in `idempotency_key` to all lines that users have a way to aggregate logs related to a request from start to finish.
* Standardized naming between different log lines as much as possible.
* Detect a TTY and produce output that's colorized and formatted.
Here's what a debug trace looks like:
And here's the more concise info trace:
[1] https://github.com/stripe/stripe-python/pull/269
> Implement `STRIPE_LOG` for stripe-ruby

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
This one is minor, but I realized after shipping #566 that it would be
nice if the number of retries was also logged for every request. This
patch follows up #566 by adding that in.
I also renamed `retry_count` to `num_retries` because I subjectively
think this name is a little better.
r? @deontologician-stripe Would you mind taking a quick look at this one as
well given that you have the most context? Thanks!
> Log `num_retries` with `STRIPE_LOG`

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
Hopefully the last tweak in a while, but a discussion on [1] tipped me
off that this was missing. Here we add a `Stripe-Account` for a request
and response to logging. Follows #566 and #567.
[1] https://github.com/stripe/stripe-node/issues/364
r? @deontologician-stripe Sorry, hopefully the last one for a while.
cc @jlomas-stripe @stripe/api-libraries
> Log `Stripe-Account` values with `STRIPE_LOG`

- README.md
- lib/stripe.rb
- lib/stripe/stripe_client.rb
- lib/stripe/util.rb
- test/stripe/stripe_client_test.rb
- test/stripe/util_test.rb
Adds support for setting `Stripe.logger` to a logger that's compatible
with `Logger` from Ruby's standard library. In set, the library will no
longer log to stdout, and instead emit straight to the logger and defer
decision on what log level to print to it.
Addresses a request in #566.
> Add support for setting a logger

- lib/stripe/webhook.rb
Currently `Stripe::Webhook.construct_event` immediately calls `JSON.parse` with the symbolize_names option. IIRC creating symbols from untrusted input can be a potential DoS attack vector, particularly on older rubies without Symbol GC?
This also makes it easier to ignore the `JSON::ParserError` exception (if the request has been verified from Stripe then it's less likely to be malformed).
> Parse webhook payload after verifying the signature header

- stripe.gemspec
The `stripe` gem installs on 1.9.3, but is unusable due to the use of keyword args.
vagrant@vagrant-ubuntu-trusty-64: ~
$ ruby -v
ruby 1.9.3p551 (2014-11-13) [x86_64-linux] Brightbox
vagrant@vagrant-ubuntu-trusty-64: ~
$ sudo gem install stripe
Fetching: multipart-post-2.0.0.gem (100%)
Fetching: faraday-0.13.1.gem (100%)
Fetching: stripe-3.3.1.gem (100%)
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.13.1
Successfully installed stripe-3.3.1
3 gems installed
vagrant@vagrant-ubuntu-trusty-64: ~
$ irb
irb(main):001:0> require 'stripe'
SyntaxError: /var/lib/gems/1.9.1/gems/stripe-3.3.1/lib/stripe.rb:207: syntax error, unexpected tLABEL
def self.set_app_info(name, version: nil, url: nil)
^
/var/lib/gems/1.9.1/gems/stripe-3.3.1/lib/stripe.rb:207: Can't assign to …
> Add correct required_ruby_version

- .travis.yml
- test/test_helper.rb
This pulls us onto the new version of stripe-mock which should be
checking parameters more accurately now that it's on OpenAPI 3.0.
> Upgrade stripe-mock to 0.2.0

- Gemfile
Because we're a library, our `Gemfile.lock` is in `.gitinore` (see [1]).
This means that you'd be otherwise be vulnerable to the whims of
whatever version of Rubocop is installed on the local system.
Because Rubocop changes fairly quickly and those changes tend to lead to
either errors or warnings on its runs, lock the gem to a particular
version in our `Gemfile`. We should try to keep the locked version
relatively current.
cc @ob-stripe
[1] http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
> Pin Rubocop dependency in `Gemfile`

- .rubocop_todo.yml
- lib/stripe/alipay_account.rb
- lib/stripe/source.rb
- lib/stripe/stripe_client.rb
- lib/stripe/stripe_object.rb
- test/stripe/alipay_account_test.rb
Removes Rubocop TODO around guard clauses and fixes the outstanding
offenses.
This is starting to get into territory that feels of more dubious value
to me, but at least it did get me writing a couple more tests, so let's
see how it goes by keeping this on.
r? @ob-stripe
> Remove Rubocop TODO around guard clauses

- .rubocop_todo.yml
- lib/stripe/api_operations/request.rb
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- test/stripe/stripe_object_test.rb
We were previously using a bit of a hack to get a free deep copy
implementation through Ruby's marshaling framework. Lint call this out
as a security problem though, and rightfully so: when combined with
unsanitized user input, unmarshaling can result in very serious security
breaches involving arbitrary code execution.
This patch removes all uses of marshal/unmarshal in favor of
implementing a deep copy method for `StripeObject`. I also reworked some
of the constants around what keys are available for `opts`. I'm still
not completely happy with the results, but I think it's going to need a
slightly larger refactor in order to get somewhere truly good.
There is what could be a breaking change for people doing non-standard
stuff with the library: the opts that we copy with an object are …
> Implement deep copy for StripeObject and remove marshal/unmarshal

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
This patch modifies the debugging-level logging logic slightly so that
if it's a `GET` request that includes a query string, we log that string
just like we would've for a request body on a `POST` or like.
This especially comes in handy when looking when trying to resolve
something like a problem with the upcoming invoices endpoint like we saw
in #576, but will be useful in a number of situations.
r? @ob-stripe
> Log query string as well as body on log debug

- stripe.gemspec
Fixes #576.
Seems difficult to add a test for this as the issue doesn't happen in stripe-ruby itself. Maybe by setting up some sort of echo server? Not sure if worth the trouble, wdyt?
> Require Faraday 0.10 for proper nested array encoding

- lib/stripe/source.rb
- test/stripe/source_test.rb
cc @stripe/api-libraries @stan-stripe @will-stripe
- Renames the `Source.delete` method to `Source.detach`. `detach` is more descriptive of what the method actually does (i.e. detaching the source object from its customer object, not actually deleting the source object).
- Alias `detach` to `delete` with a deprecation warning to avoid a breaking change. We should remove the `delete` method in next major version.
> detach method for detaching sources from customers

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Backtracks a little bit #586 by bringing back custom `StripeObject`
encoding and decoding methods for Ruby's `Marshal`. These work by just
persisting values and some opts, and skipping everything else. It's
mostly the same as what we had before, but implemented a little more
cleanly so that we don't actually need to invoke `Marshal` anywhere
ourselves.
In #586 we still managed to remove all the uses of `Marshal` in our own
codebase to make the linter happy. Even though we wouldn't recommend the
use of `Marshal`, this code at least enables it for anyone using a Rails
cache or similar mechanism.
Addresses #90.
> Implement custom Marshal encoder/decoder for `StripeObject`

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Minor fix: I noticed that `deep_copy` always returns a `StripeObject` instance. This PR fixes it so it returns an instance of the same class that is being copied.
> Maintain class in deep_copy

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Fixes #524 by implementing the workaround suggested by @jakeonrails. It's a bit of a hack but it works and makes the library compatible with `awesome_print` even when the object has a `method` field.
> Call Object#method if method accessor is called with arguments

- lib/stripe/invoice.rb
- lib/stripe/order.rb
- lib/stripe/subscription.rb
- test/stripe/subscription_test.rb
Fixes #554.
Back in #467, we introduced support for transparently turning the `items` parameter to a hash of hashes if needed when calling `Subscription#create` or `Subscription#update`. However, this failed to handle the case where you'd retrieve a subscription, set the `items` attribute and save the subscription.
There were actually two different issues going on in the above case:
1. The parameter was not being converted to a Hash if needed.
2. Even if the user provided a Hash directly, the library would try to unset the fields on the existing `ListObject` of the subscription's `items` attribute.
This PR fixes both issues, by calling `Util.array_to_hash` and by passing `nil` for the original value when serializing `items`.
It also calls …
> Encode arrays as hashes when needed

- .rubocop_todo.yml
- lib/stripe/api_operations/request.rb
- lib/stripe/util.rb
- test/stripe/util_test.rb
Excludes `idempotency_key` from opts to persist between API requests.
Obviously the same idempotency key is not something that we ever want to
use again.
Fixes #598.
r? @ob-stripe
> Don't persist `idempotency_key` option between API requests

- lib/stripe.rb
- lib/stripe/account.rb
- lib/stripe/api_operations/nested_resource.rb
- lib/stripe/application_fee.rb
- lib/stripe/customer.rb
- lib/stripe/transfer.rb
- test/stripe/account_external_accounts_operations_test.rb
- test/stripe/account_login_links_operations_test.rb
- test/stripe/api_operations_test.rb
- test/stripe/application_fee_refunds_operations_test.rb
- test/stripe/customer_sources_operations_test.rb
- test/stripe/transfer_reversals_operations_test.rb
This PR is an attempt at fixing #420. It adds a `nested_resource_class_methods` DSL method that `StripeObject`s can use to define methods to access a nested resource without needing to retrieve the owning resource first.
E.g. you can now create a card on a customer like this:
```ruby
card = Stripe::Customer.create_card(
"cus_...",
token: "tok_visa"
)
```
and update it like this:
```ruby
updated_card = Stripe::Customer.update_card(
"cus_...",
"card_...",
exp_month: 12,
exp_year: 2020
)
```
This is helpful for users looking to minimize the number of outgoing API requests.
> Nested resource class methods

- lib/stripe/account.rb
- lib/stripe/api_operations/nested_resource.rb
- lib/stripe/customer.rb
- test/stripe/api_operations_test.rb
Makes the `operations` argument to `nested_resource_class_methods` required and adds explicit lists to any invocations that were missing one.
The impetus here is that I think it's more easily digestible if each call site is explicit about what operations it supports and therefore which methods it's about to create on the class.
r? @ob-stripe This is definitely the pedant in me, but I kind of like seeing the explicit list of operations for each of these, and most call sites had to define an explicit list from the beginning anyway sine they don't support all operations. Thoughts?
> Add explicit operations list everywhere

- .travis.yml
- test/stripe/exchange_rate_test.rb
- test/test_helper.rb
stripe-mock 0.4.0 comes with the up-to-date exchange rates API. Here we
bump the required version and remove the manual exchange rate stubbing
in stripe-ruby's test suite.
r? @ob-stripe
> Remove manual exchange rate stubbing

- lib/stripe/file_upload.rb
- test/stripe/file_upload_test.rb
cc @stripe/api-libraries @remi-stripe 
Fixes #610.
Back in #508, we reintroduced support for passing `File` instances, but not `Tempfile` instances. (I'm not sure why `Tempfile` is not a subclass of `File` but ¯\\\_(ツ)\_/¯)
This PR adds support for passing `Tempfile` instances, which is useful for e.g. opening a remote file via `open-uri`.
> Support Tempfiles in file_upload creation requests

- lib/stripe/stripe_client.rb
- test/stripe/invoice_test.rb
- test/stripe/stripe_client_test.rb
As discussed in #608, we currently have a problem where Faraday
deconstructs a query string that we encode and strips out any of the
array index numbers that we added. It's not too clear on why it does
this, but it appears to be built in at a pretty low level and hard to
change.
I spent a little time on this and it turns out that we can avoid the bad
code by depending on Faraday's `params` accessor on a request instead of
trying to do the encoding ourselves. Webmock has a pretty hard time
detecting the difference, but you can see some before and after encoding
here.
Before:
```
I, [2017-12-06T17:41:23.083942 #36737]  INFO -- : get
http://localhost:12111/v1/invoices/upcoming?customer=cus_123&subscription_items%5B%5D%5Bplan%5D=gold&subscription_items%5B%5D%5Bquantity%5D=2
```
After:
```
I, …
```
> Fix encoding of arrays that are sent in query strings

- .rubocop_todo.yml
- lib/stripe/errors.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
A few weeks back a new error type `idempotency_error` was introduced in the
API. I put it in to respond to #503, but then forgot to add support for it in
this library. This patch introduces a new exception class that represents it.
r? @ob-stripe One thing that's a little janky about this patch is that we were
previously just doing error type switching off of the returned status code, but
here we add a second ladder on error type because a 400 becomes ambiguous. This
works fine conceptually, but it might be that we just have a single ladder on
error type and ignore the status code completely (this is how stripe-node works
for example). Thoughts?
> Introduce new `IdempotencyError` type

- .gitignore
- Gemfile
- README.md
- test/test_helper.rb
Adds support for coveralls.io: https://coveralls.io/github/stripe/stripe-ruby
> Add support for coveralls.io

- lib/stripe/file_upload.rb
Use duck typing to detect `File`-like objects rather than directly checking the class. This is the same strategy used by rest-client: https://github.com/rest-client/rest-client/blob/f450a0f086f1cd1049abbef2a2c66166a1a9ba71/lib/restclient/payload.rb#L55.
Thanks @kimroen for the suggestion!
Fixes #615.
> Use duck typing to detect File-like objects

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
cc @stripe/api-libraries @ashkan18 
Replaces #602. The PR has been open for a while and it's been bothering me :P
This is exactly the same as #602, except that `NilClass.include NilWithToHash` was replaced with `NilClass.send(:include, NilWithToHash)` so that the test suite works with Ruby 2.0.
> Skip calling to_hash for nil

- .rubocop_todo.yml
- lib/stripe.rb
- lib/stripe/topup.rb
- lib/stripe/util.rb
- test/stripe/topup_test.rb
This add standard retrieve, create and update client support for the new `/v1/topups` endpoint.
r? @apakulov-stripe @ccontinanza-stripe @chellman-stripe @kenneth-stripe @miguel-stripe
r? @stripe/api-libraries
> Add support for /v1/topups endpoints

- .rubocop_todo.yml
- lib/stripe/api_operations/save.rb
- lib/stripe/stripe_object.rb
- lib/stripe/subscription.rb
- test/stripe/stripe_object_test.rb
So we have a bit of a problem right now when it comes to replacing a
`StripeObject` that's embedded in an API resource.
Most of the time when someone does this, they want to _replace_ an
object embedded in another object. Take setting a source on a
subscription for example:
``` ruby
subscription.source = {
object: 'card',
number: 123,
}
subscription.save
```
In the case above, the serialized parameters should come out as:
```
source[object]=card&source[number]=123
```
That should apply even if the previous source had something else set on
it which we're not going to set this time -- say an optional parameter
like `source[address_state]`. Those should not be present at all in the
final serialized parameters.
(Another example is setting a `payout_schedule` as seen in #631 which is
PR is …
> Fix replacement of non-`metadata` embedded `StripeObjects`

- lib/stripe/stripe_object.rb
The test suite is currently throwing a bunch of warnings from some
recent changes I made -- although we initialize `@additive_params` when
setting one with `self.additive_object_param`, we don't when we check
one with `self.additive_object_param?`. This often isn't a problem
because every API resource sets `metadata`, but it is from the test
suite and probably for vanilla `StripeObject`s too.
> Initialize instance variable on the getter too

- .travis.yml
- test/stripe/account_external_accounts_operations_test.rb
- test/test_helper.rb
The most important changes here are that deleted objects are now
represented more accurately, and that IDs used in URLs are "reflected"
back into responses so that test suites can treat return objects a
little more realistically than they could before.
This should resolve incompatibilities between `stripe-ruby` and newer
versions of `stripe-mock`.
> Upgrade `stripe-mock` to v0.12.0

- README.md
I don't remember why I wrote this originally, but found it sitting
locally uncommitted. It seems like a useful example to have in the
README, so add it in.
r? @ob-stripe
> Add a README section for globally configuration an API version

- .travis.yml
- test/stripe/file_upload_test.rb
- test/test_helper.rb
`stripe-mock` can now respond accurately for file API endpoints thanks
to a few improvements in how it handles `multipart/form-data` payloads
and the OpenAPI spec.
Here we upgrade `stripe-mock` to 0.15.0 and remove the manual stubbing
that we had previously.
r? @ob-stripe
> Move file upload tests over to be handled by `stripe-mock`

- .rubocop_todo.yml
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
If specifying both query parameters in a path/URL down to Faraday (e.g.,
`/v1/invoices/upcoming?coupon=25OFF`) _and_ query parameters in a hash
(e.g., `{ customer: "cus_123" }`), it will silently overwrite the ones
in the path with the ones in the hash. This can cause problems where
some critical parameters are discarded and causes an error, as seen in
issue #646.
This patch modifies `#execute_request` so that before going out to
Faraday we check whether the incoming path has query parameters. If it
does, we decode them and add them to our `query_params` hash so that
all parameters from either place are preserved.
Fixes #646.
r? @remi-stripe
> Merge query parameters coming from path with `params` argument

- lib/stripe/version.rb
- test/stripe/customer_test.rb
- test/stripe/order_test.rb
- test/stripe/subscription_item_test.rb
I found a bug recently in stripe-mock which causes it not to actually be
validating that parameters not in the spec are not being sent (the
actual Stripe API does check for this).
After applying a fix, I found that stripe-ruby's test suite no longer
passes against it, and the reason is that there are some subtle mistakes
throughout. This patch corrects them to be in line with what the API
actually expects.
r? @stripe/api-libraries
> Fix some parameters being sent in tests

- .travis.yml
Adds Ruby 2.5 to the test matrix.
I also switched us over to aliases of each major Ruby version because I
think it makes more sense to be locked to whatever the latest release in
each is.
r? @ob-stripe
> Add Ruby 2.5 to test matrix + use aliases

- lib/stripe/util.rb
- test/stripe/util_test.rb
This changes the predicate supplied to the #colorize method to ensure
that if a logger is set, the colorizing ANSI escape codes are not applied.
This definitely appears to have been the intention behind the original
implementation, but the tests didn't reflect how .log_internal was
actually called. In reality, it is always supplied with an `out:`
argument, not nil. This caused all logger bound output to also be
colorized.
> Do not colorize output destined for configured logger

- .rubocop.yml
- .rubocop_todo.yml
- lib/stripe/util.rb
Remi pointed out in #666 that we basically just have to keep adding more
more onto the `Max` exception for both these rules every time we add a
new API resource.
Here I suggest that we modify the check on method length in two ways:
1. Permanently disable the cop on `Util.object_classes`. This is just
going to keep growing until we change are approach to it.
2. Choose a more reasonable maximum of 50 lines for elsewhere (IMO, the
default of 10 is just too short). Most of our methods already come in
below this, but there's a couple outliers like `#execute_request` in
`StripeClient`. If we knock over some of those, we could lower this
number again, but I suspect that we'd probably want somewhere closer
to 30 (instead of 10) event then.
I also disable the check on module length completely. I'm …
> Rubocop: Cap method length at 50 lines + disable module length

- lib/stripe/topup.rb
- test/stripe/topup_test.rb
cc @stripe/api-libraries @foresthu-stripe 
Add cancel support for topups.
> Add cancel support for topups

- lib/stripe/invoice.rb
- lib/stripe/order.rb
- lib/stripe/subscription.rb
- lib/stripe/util.rb
- test/stripe/subscription_test.rb
- test/stripe/util_test.rb
Changes all arrays from classic Rack encoding:
``` sh
arr[]=...&arr[]=...&arr[]=...
```
To integer-indexed encoding:
``` sh
arr[0]=...&arr[1]=...&arr[2]=...
```
We think that this should be tractable now that we've fully converted
all endpoints over to the new AbstractAPIMethod infrastructure on the
backend (although we should do a little more testing to make sure that
all endpoints still work).
As part of the conversion, we also remove any places that we were "spot
encoding" to get required integer-indexed syntax. This should now all be
built in.
cc @stevene-stripe @zanker-stripe
> Integer-index encode all arrays

- lib/stripe/bitcoin_receiver.rb
Tests pass:
```
» bundle exec rake test
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'test_frameworks' settings.
/Users/tomer/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:400: warning: assigned but unused variable - context
Loaded suite /Users/tomer/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.3.1/lib/rake/rake_test_loader
Started
..........................................................................................................................................
..........................................................................................................................................
............................................................................................... …
```
> Remove ability to perform edit-actions on bitcoin receivers

- test/stripe/api_resource_test.rb
I was testing with a new version of stripe-mock and it caught a few
problems with query parameter validation on. This patch contains some
minor fixes to address them.
r? @remi-stripe
> Minor test fixes

- .travis.yml
- test/test_helper.rb
Upgrades to the most recent version of stripe-mock now that we've got a
few more fixes into both its implementation and into stripe-ruby's test
suite.
> Upgrade stripe-mock to 0.30.0

- lib/stripe/util.rb
Using String#capitalize and String#empty? collapses the definition down to a more readable one liner. Having it separate to normalize_headers doesn't add much seeing as it isn't used anywhere else.
> Remove Util.titlecase_parts method

- lib/stripe/stripe_object.rb
This implements the switch to keyword arguments as described in the comment.
> Use keyword args for StripeObject#update_attributes

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
Overrides `#eql?` (hash equality) and `#hash` so that Stripe objects can
be used more easily as Hash keys and that certain other frameworks that
rely on these methods will have an easier time (e.g. RSpec's `change`,
see #687).
I think this might be a little controversial if we weren't already
overriding the `#==` implementation, but because we are, I think it
makes sense to extent it to these two methods as well.
Fixes #687.
r? @ob-stripe
> Override `StripeObject#eql?` and `#hash` to produce more optimistic equivalency

- lib/stripe.rb
- lib/stripe/util.rb
- lib/stripe/webhook_endpoint.rb
- test/stripe/webhook_endpoint_test.rb
Flagging that with the most recent local fixtures an Order test is failing while validating `items`
> Add support for the Webhook Endpoint resource

- lib/stripe/invoice.rb
- test/stripe/coupon_test.rb
- test/stripe/invoice_test.rb
> Add new methods to the Invoice resource

- .gitignore
- .rubocop_todo.yml
- lib/stripe.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
This PR adds in basic client telemetry that for now only includes timing information. The telemetry is sent back as a sidecar payload in an HTTP header of:
`X-Stripe-Client-Telemetry`
With a JSON payload format of:
```
{ 
"last_request_metrics": {
"request_id": "...",
"request_duration": 1.23
}
}
```
By sending as a sidecar http header we avoid an extraneous network call at the cost of only being able to track the previous request.
Adding in this telemetry will allow stripe to help diagnose latency and other connection issues as well as provide a space to augment future telemetry data.
Telemetry needs to be opted into by setting:
```
Stripe.enable_telemetry = true
```
And can be disabled at any time by toggling that flag (the value is not cached)
> Adding metadata header to client requests

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
Related to #696 making a minor change to make the telemetry payload more specific in terms of timing units.  I'm making the payload specific that it is in milliseconds and enforcing that in the ruby time difference. This is important so we can keep cross binding payloads consistent.
r? @ob-stripe @brandur-stripe
> Making stripe telemetry more specific in terms of units

- .travis.yml
- Gemfile
- lib/stripe/stripe_client.rb
- stripe.gemspec
- test/test_helper.rb
This changes the library's default connection over to use the adapter
for `Net::HTTP::Persistent`, which is a connection pooling library for
Ruby.
In the long run, I think we should probably just drop Faraday ... the
amount of value it's getting us is extremely tenuous and its API is
difficult to work with. I hate to do it at this point though because
technically people could be writing custom middleware for it.
r? @ob-stripe
> Use Faraday's `Net::HTTP::Persistent` adapter

- lib/stripe/stripe_client.rb
Tweaks telemetry implementation slightly to be inline with the recent
implementation in stripe-php. Telemetry isn't much good if a request ID
wasn't present, so we only send telemetry if it was.
r? @akropp-stripe
> Only send telemetry if request ID was present

- Gemfile
- stripe.gemspec
We require net-http-persistent 3.0.0 or more recent, but Faraday doesn't support this version until 0.13.0 (cf. https://github.com/lostisland/faraday/pull/619). Bump the minumum Faraday version in the gemspec file.
Fixes #700.
Also opportunistically bump rack version in the Gemfile to fix a security vulnerability reported by GitHub (https://nvd.nist.gov/vuln/detail/CVE-2018-16471).
> Bump Faraday minimum version to 0.13.0

- lib/stripe/account.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_object_test.rb
This pull request a few typo/misspellings in comments/error messages.
> Fix typo/misspell in comments & error messages

- lib/stripe/oauth.rb
- test/stripe/oauth_test.rb
Connect with Express accounts uses a slightly different version of the
OAuth authorize URL [1] in that it's prefixed with `/express`.
Here we add a new option to `Stripe::OAuth.authorize_url` which allows
`express: true` to be passed in to generate the Express variant.
Note that the token endpoint has no equivalent so we don't need the
option there.
Fixes #717.
r? @ob-stripe
[1] https://stripe.com/docs/connect/oauth-reference#express-account-differences
> Generate OAuth authorize URLs for express accounts

- .travis.yml
- test/test_helper.rb
r? @remi-stripe 
Bump stripe mock-version after release https://github.com/stripe/stripe-mock/pull/132
> bump strip mock version to 0.40.1

- .travis.yml
- test/openapi/README.md
- test/stripe_mock.rb
- test/test_helper.rb
First attempt at embedding OpenAPI spec and fixtures files directly in the repo and using those for the test suite. Pretty rough, but it works.
Possible improvements:
- ~better logs / error handling~ (done)
- ~automatically choose an unused port~ (done)
- detect "Listening for HTTP on port" in stripe-mock output instead of sleeping for 1 second
> Detect custom OpenAPI spec file and start stripe-mock from test suite

- lib/stripe/account.rb
- test/stripe/account_test.rb
Properly serialize `individual` on Account objects.
> Properly serialize `individual` on Account objects

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
In #741 I tried to do something too clever by replacing instances of
`Faraday::UploadIO` found in parameters with a human-readable string to
improve `STRIPE_LOG` logging output.
I thought I'd tested it at the time, but apparently not (or not well
enough), and this change caused the regression detailed in #742.
My findings about how Faraday encodes multipart were apparently wrong
and it does use these parameters, so here we remove the step where we
try to nicen them for logging. The logs look a little worse, but it's
not that big of a deal.
I've tested this patch against the API and confirmed that it addresses
the problem.
Fixes #742.
r? @ob-stripe
> Remove attempt to nicen `UploadIO` in logs

- lib/stripe/stripe_object.rb
In some cases there can be a method that's detected with
`method_defined?`, but which cannot be removed with `remove_method`,
even though it's on the same class. The only case so far that we've
noticed this is when a class is reopened for monkey patching like in
issue #749.
We'll still try to discourage this sort of use, but here we swallow the
error and issue a warning so at least the program doesn't crash.
Fixes #749.
r? @ob-stripe
> Catch error and warn if unable to remove a method

- .travis.yml
- test/stripe/checkout/session_test.rb
- test/test_helper.rb
This adds support for retrieving a Checkout Session via the API and also changes the shape of the resource to have more details.
> Add support for retrieving a Checkout Session

- .travis.yml
- lib/stripe/terminal/location.rb
- lib/stripe/terminal/reader.rb
- test/stripe/terminal/location_test.rb
- test/stripe/terminal/reader_test.rb
- test/test_helper.rb
> Add support for Terminal Location and Reader deletion

- lib/stripe/api_operations/delete.rb
- lib/stripe/charge.rb
- test/stripe/account_test.rb
- test/stripe/apple_pay_domain_test.rb
- test/stripe/coupon_test.rb
- test/stripe/customer_test.rb
- test/stripe/ephemeral_key_test.rb
- test/stripe/invoice_item_test.rb
- test/stripe/invoice_test.rb
- test/stripe/plan_test.rb
- test/stripe/product_test.rb
- test/stripe/radar/value_list_item_test.rb
- test/stripe/radar/value_list_test.rb
- test/stripe/recipient_test.rb
- test/stripe/sku_test.rb
- test/stripe/subscription_item_test.rb
- test/stripe/subscription_test.rb
- test/stripe/terminal/location_test.rb
- test/stripe/terminal/reader_test.rb
- test/stripe/webhook_endpoint_test.rb
Opening this PR for early feedback.
Things are much easier/less hacky than Python here since Ruby supports class methods and instance methods with same names.
We'll probably need to do some refactoring around the helper URL methods for non-CRUDL methods though.
> Static methods for delete

- test/stripe/file_test.rb
- test/stripe/file_upload_test.rb
cc @brandur-stripe @remi-stripe 
stripe-ruby encodes nested parameters correctly in multipart requests, but let's add a test just to ensure we don't introduce regressions in the future (e.g. if we get rid of Faraday).
> Include file_link_data parameter in file creation test

- lib/stripe/file.rb
- test/stripe/file_test.rb
When uploading a file, we previously made a check on whether it
supported both `#read` and `#path` before wrapping it in a
`Faraday::UploadIO` and sending it off. The second check on `#path`
isn't strictly necessary, and as reported in #761 can prevent objects
created by `open-uri` from being compatible with file upload.
Here we remove the check `#path` so that we just require that objects
support `#read`, and in addition error when an object is passed that's
not file-compatible and not a string. This should prevent users from
seeing the very confusing "Invalid hash" error in these situations.
Fixes #761.
r? @ob-stripe
> Relax constraints on objects that we'll accept as a file

- lib/stripe/checkout/session.rb
- lib/stripe/issuing/authorization.rb
- lib/stripe/issuing/card.rb
- lib/stripe/issuing/cardholder.rb
- lib/stripe/issuing/dispute.rb
- lib/stripe/issuing/transaction.rb
- lib/stripe/radar/value_list.rb
- lib/stripe/reporting/report_run.rb
- lib/stripe/reporting/report_type.rb
- lib/stripe/terminal/connection_token.rb
- lib/stripe/terminal/location.rb
- lib/stripe/terminal/reader.rb
Simplify inheritance to make code look a bit more like codegen version. There's no need to explicitly mention root module here since all the classes are defined inside it anyway.
r? @rattrayalex-stripe
> Simplify inheritance for nested classes

- lib/stripe/coupon.rb
- lib/stripe/credit_note.rb
- lib/stripe/file_link.rb
- lib/stripe/invoice.rb
- lib/stripe/invoice_item.rb
- lib/stripe/order.rb
- lib/stripe/payment_method.rb
- lib/stripe/payout.rb
- lib/stripe/product.rb
- lib/stripe/recipient.rb
- lib/stripe/subscription_schedule.rb
- lib/stripe/tax_rate.rb
- lib/stripe/transfer.rb
- lib/stripe/webhook_endpoint.rb
Codegen sorts normal/non-custom methods by names when it decides to include/extend the class with an appropriate module. This PR changes the order of includes/extens to closer match codegen in classes that are otherwise the same or alsmost the same between current state of the library and codegen.
r? @rattrayalex-stripe
> Sort includes/extends by method name for consistency

- lib/stripe/radar/value_list_item.rb
- lib/stripe/sigma/scheduled_query_run.rb
- test/stripe/api_resource_test.rb
A follow up for https://github.com/stripe/stripe-ruby/pull/769 addressing some classes that codegen missed on the first pass.
r? @rattrayalex-stripe
> More simplifying inheritance

- lib/stripe/account.rb
- lib/stripe/api_operations/delete.rb
- lib/stripe/source.rb
- lib/stripe/subscription_item.rb
- lib/stripe/subscription_schedule.rb
- lib/stripe/util.rb
In some places in the code we call `Util.normalize_opts` on `opts` before passing `opts` to `request` or `Util.convert_to_stripe_object `
Thing is, `request` method does it anyways internally here: https://github.com/stripe/stripe-ruby/blob/v4.16.0/lib/stripe/api_operations/request.rb#L10
And `initialize_from` does it here: https://github.com/stripe/stripe-ruby/blob/v4.16.0/lib/stripe/stripe_object.rb#L414
The only "weak" spot was `Util.convert_to_stripe_object`, so I made sure it explicitly normalizes as well.
With this, we can remove `Util.normalize_opts` from a bunch of resources and make them cleaner and more codegen-friendly.
r? @ob-stripe
> Remove explicit Util.normalize_opts calls

- .travis.yml
- test/stripe/api_resource_test.rb
- test/stripe/payment_intent_test.rb
- test/test_helper.rb
Fix a few tests to work with latest stripe-mock.
> Bump stripe-mock to 0.57.0 and fix tests

- lib/stripe/order.rb
- test/stripe/order_test.rb
`Order#pay` does not require arguments when an order is attached to a customer. Let's remove the requirement from the API to make paying orders a bit cleaner (`order.pay` vs `order.pay({})`).
Removing this requirement will not throw an argument error locally if the order does not have a customer and is attempted to be paid via the API. However, the API will throw a more descriptive error back to the user if the `source` param is committed which provides a better UX.
> Order#pay without arguments

- README.md
> Fix examples to not use hash rockets

- README.md
- lib/stripe.rb
cc @stripe/api-libraries-releasers 
Enable request latency telemetry by default, and add instructions to the README file for disabling request telemetry.
(I also made a bunch of other changes to the README file to make my linter happy.)
> Enable request latency telemetry by default

- lib/stripe/stripe_client.rb
Add space at the end of the second line so the complete message separates the word `not` and `working`
message before
```
Stripe::APIConnectionError: Unexpected error communicating when trying to connect to Stripe. You may be seeing this message because your DNS is notworking.  To check, try running `host stripe.com` from the command line.
```
message after
```
Stripe::APIConnectionError: Unexpected error communicating when trying to connect to Stripe. You may be seeing this message because your DNS is not working.  To check, try running `host stripe.com` from the command line.
```
> Fix formatting in ConnectionFailed error message

- stripe.gemspec
I wanted to test GitHub's new Package Registry feature and publish the latest stripe-ruby gem there. We need to add a custom `github_repo` entry to the metadata, because otherwise GitHub uses the gem's name as the repository's name, which in our case causes it to fail because the gem is called `stripe` and the repository is called `stripe-ruby`.
While I was at it, I also added standard metadata as documented on https://guides.rubygems.org/specification-reference/#metadata.
> Add gem metadata

- lib/stripe/resources/account.rb
- lib/stripe/resources/credit_note.rb
- lib/stripe/resources/dispute.rb
- lib/stripe/resources/invoice.rb
- lib/stripe/resources/issuing/authorization.rb
- lib/stripe/resources/issuing/card.rb
- lib/stripe/resources/payment_intent.rb
- lib/stripe/resources/payment_method.rb
- lib/stripe/resources/payout.rb
- lib/stripe/resources/review.rb
- lib/stripe/resources/setup_intent.rb
- lib/stripe/resources/source.rb
- lib/stripe/resources/subscription_schedule.rb
- lib/stripe/resources/topup.rb
- lib/stripe/resources/transfer.rb
r? @ob-stripe 
cc @stripe/api-libraries @brandur-stripe 
In ea736eba1b8f33d8febbf0b1be0957f34f7b04db, on https://github.com/stripe/stripe-ruby/pull/790, we changed most uses of `initialize_from` to be `Util.convert_to_stripe_object`. We believed this to be equivalent, but this was incorrect; as @AnotherJoSmith  [pointed out](https://github.com/stripe/stripe-ruby/pull/790#issuecomment-508257388), this returned new objects without mutating instances in-place (or, more precisely, copying over previous attributes). 
For example, I believe this would have broken flows like this: 
```rb
charge = Stripe::Charge.retrieve id
charge.capture
assert charge.captured == true # broken!
```
I hope to implement a smoother fix to this in a follow-on, but for now, I reverted the offending commit, and …
> Revert back to `initialize_from` from `Util.convert_to_stripe_object`

- lib/stripe/api_resource.rb
- test/stripe/api_resource_test.rb
Raises a slightly more helpful error message when passing a non-string
to a custom method (currently, it reads "no implicit conversion of Hash
into String", which is terrible).
This a partial remediation for the problem encountered in #809.
r? @ob-stripe
> Better error message when passing non-string to custom method

- lib/stripe/errors.rb
- lib/stripe/stripe_client.rb
Makes the `code` parameter on `CardError` named instead of positional.
This makes it more consistent with the rest of the constructor's
parameters and makes instantiating `CardError` from `StripeClient`
cleaner.
This is a minor breaking change so we're aiming to release it for the
next major version of stripe-ruby.
(Found this while looking through TODOs in the code to fix up for V5.)
r? @ob-stripe
---
Note: Targets the branch `integration-v5` in #815 instead of `master`.
> Make `CardError`'s `code` parameter named instead of positional

- .travis.yml
- Gemfile
- README.md
r? @ob-stripe 
Clean up a few things that are no longer needed after #817.
> Ruby minimum version increase followup

- .travis.yml
- lib/stripe/resources/balance_transaction.rb
- test/stripe/balance_transaction_test.rb
- test/test_helper.rb
r? @ob-stripe 
Flagging I made the modification manually while we work on fixing the autogen internally for ruby!
> Move Balance History to /v1/balance_transactions and add tests

- lib/stripe/api_operations/list.rb
- test/stripe/list_object_test.rb
Remove `all` alias for `list` methods.
> Remove all alias for list methods

- lib/stripe/api_resource.rb
- lib/stripe/resources/account.rb
- lib/stripe/resources/charge.rb
- lib/stripe/resources/credit_note.rb
- lib/stripe/resources/dispute.rb
- lib/stripe/resources/invoice.rb
- lib/stripe/resources/issuing/authorization.rb
- lib/stripe/resources/issuing/card.rb
- lib/stripe/resources/order.rb
- lib/stripe/resources/payment_intent.rb
- lib/stripe/resources/payment_method.rb
- lib/stripe/resources/payout.rb
- lib/stripe/resources/review.rb
- lib/stripe/resources/setup_intent.rb
- lib/stripe/resources/source.rb
- lib/stripe/resources/subscription_schedule.rb
- lib/stripe/resources/topup.rb
- lib/stripe/resources/transfer.rb
- lib/stripe/util.rb
- test/stripe/api_resource_test.rb
r? @ob-stripe 
cc @brandur-stripe 
Goal is to solve problems like https://github.com/stripe/stripe-ruby/pull/806 but also move ~everything to make requests the same way, with a single function call (except truly exceptional cases, where we need logic in handlers for backcompat etc).
Have updated this somewhat per feedback below.
> Unify request/response handling

- lib/stripe/resources/subscription_item.rb
- lib/stripe/resources/subscription_schedule.rb
- test/stripe/subscription_item_test.rb
> [codegen] Add `SubscriptionItem.create_usage_record` method

- .rubocop.yml
- .rubocop_todo.yml
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
Tweaks the retry logic to be a little more like stripe-node's. In
particular, we also retry under these conditions:
* If we receive a 500 on a non-`POST` request.
* If we receive a 503.
I made it slightly different from stripe-node which checks for a 500
with `>= 500`. I don't really like that -- if we want to retry specific
status codes we should be explicit about it.
We're actively re-examining ways on how to make it easier for clients to
figure out when to retry right now, but I figure V5 is a good time to
tweak this because the modifications change the method signature of
`should_retry?` slightly, and it's technically a public method.
r? @ob-stripe
---
Note: targets the V5 integration branch in #815.
> Tweak retry logic to be a little more like stripe-node

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
I messed up in #828 by (1) accidentally flipping the comparison against
`:post` when checking whether to retry on 500, and (2) forgetting to
write new tests for the condition, which is how (1) got through.
This patch fixes both those problems. Thanks @rattrayalex-stripe for the
tip off! Oops.
r? @ob-stripe
> Fix inverted sign for 500 retries

- lib/stripe.rb
- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
- test/stripe_test.rb
I noticed that we had a couple of other deprecated methods on `Stripe`
and `StripeObject` that have been around for a long time. May as well
get rid of them too -- luckily they were using `Gem::Deprecate` so
they've been producing annoying deprecated warnings for quite a while
now.
r? @ob-stripe Sorry for the deluge OB. Last one I think.
> Remove a few more very old deprecated methods

- lib/stripe.rb
- lib/stripe/connection_manager.rb
- lib/stripe/stripe_client.rb
- test/stripe/connection_manager_test.rb
- test/stripe/stripe_client_test.rb
Adds a few basic features around connection and connection manager
management:
* `clear` on connection manager, which calls `finish` on each active
connection and then disposes of it.
* A centralized cross-thread tracking system for connection managers in
`StripeClient` and `clear_all_connection_managers` which clears all
known connection managers across all threads in a thread-safe way.
The addition of these allow us to modify the implementation of some of
our configuration on `Stripe` so that it can reset all currently open
connections when its value changes.
This fixes a currently problem with the library whereby certain
configuration must be set before the first request or it remains fixed
on any open connections. For example, if `Stripe.proxy` is set after a
request is made from the …
> Reset connections when connection-changing configuration changes

- .rubocop.yml
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
I ended up having to relax the maximum method line length in a few
previous PRs, so I wanted to try one more cleanup pass in
`execute_request` to see if I could get it back at all.
The answer was "not by much" (without reducing clarity), but I found a
few places that could be tweaked. Unfortunately, ~50 lines is probably
the "right" length for this method in that you _could_ extract it
further, but you'd end up passing huge amounts of state all over the
place in method parameters, and it really wouldn't look that good.
r? @ob-stripe
---
Note: targets the V5 integration branch in #815.
> Minor cleanup in `StripeClient`

- lib/stripe/resources/invoice.rb
- test/stripe/invoice_test.rb
Add a `Stripe::Invoice.list_upcoming_line_items` method, to replace the ugly `Stripe::Invoice.retrieve("upcoming").lines.list` invocation.
> Add `Invoice.list_upcoming_line_items` method

- lib/stripe/connection_manager.rb
One thing I forgot to look into was how long Ruby will hold a connection
open by default. It turns out that the language default is very low at
only two seconds. Here we increase it to 30 seconds, which is a more
reasonable default. I took this number from Go's `DefaultTransport`,
which seems to have been working pretty well so far.
I tested with a script that keeps a connection idle to Stripe for a long
period of time before issuing a new request and everything seems to be
working well.
r? @ob-stripe
> Increase connection keep alive timeout to 30 seconds

- lib/stripe/connection_manager.rb
A tiny refactor where we extract the warning you get when setting SSL
verify mode to `VERIFY_NONE` into its own method. No real impetus for
this except that it extracts very nicely, and that gets us to a smaller
`create_connection` method.
r? @ob-stripe
> Extract SSL verify none warning to its own method

- lib/stripe/errors.rb
- test/stripe/errors_test.rb
When requesting error#request_id it returned nil although the request id was available in the request headers. With version 5 and switch to Net::HTTP this value is now a string, not a symbol which means that the request_id was not stored on the error correctly.
This picture shows a live request to stripe:
> Transfer the request_id from the http_headers to error.

- .rubocop.yml
- .rubocop_todo.yml
- test/stripe/stripe_client_test.rb
Follows up #845 to make sure that this sort of regression is much more
difficult in the future by adding a test that makes sure a request ID is
threaded all the way from an HTTP response back through to an error
object. I verified that the test failed before #845 came in.
r? @ob-stripe
> Add a test to make sure request IDs make it into error objects

- test/stripe/stripe_client_test.rb
Previously, we had quite a few error tests that were written like this:
``` ruby
begin
client.execute_request(:post, "/v1/charges")
rescue Stripe::InvalidRequestError => e
assert_equal(404, e.http_status)
assert_equal(true, e.json_body.is_a?(Hash))
end
```
The trouble with that pattern is that although it'll _usually_ work,
the test will incorrectly pass if no error at all is thrown because the
`rescue` never activates and therefore the assertions never run.
We change them to use `assert_raises` like so:
``` ruby
e = assert_raises Stripe::InvalidRequestError do
client.execute_request(:post, "/v1/charges")
end
assert_equal(404, e.http_status)
assert_equal(true, e.json_body.is_a?(Hash))
```
The weird part is that many of the tests were already using
`assert_raises`, so here we're just …
> Change some error tests to use `assert_raises`

- lib/stripe/connection_manager.rb
- lib/stripe/stripe_client.rb
- test/stripe/connection_manager_test.rb
- test/stripe/stripe_client_test.rb
Introduces a system for garbage collecting connection managers in an
attempt to solve #850.
Previously, the number of connection managers (and by extension the
number of connections that they were holding) would stay stable if a
program used a stable number of threads. However, if threads were used
disposably, the number of active connection managers out there could
continue to grow unchecked, and each of those could be holding one or
more dead connections which are no longer open, but still holding a file
descriptor waiting to be unlinked in disposed of by Ruby's GC.
This PR introduces a connection manager garbage collector that runs
periodically whenever a new connection manager is created. Connection
managers get a timestamp to indicate when they were last used, and the
GC runs through …
> Introduce system for garbage collecting connection managers

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
As seen in stripe-node, adds support for the `Stripe-Should-Retry`
header which is sent by the API when it explicitly would like us to
either retry or _not_ retry.
I'll add `Retry-After` separately at some point, but I punted it on it
for now given that we're not using it yet.
See: https://github.com/stripe/stripe-node/pull/692
r? @ob-stripe
> Support `Stripe-Should-Retry` header

- lib/stripe/connection_manager.rb
- lib/stripe/stripe_client.rb
- lib/stripe/util.rb
- test/stripe/connection_manager_test.rb
- test/stripe/stripe_client_test.rb
Drops the use of `Time.now` in favor of using the system's monotonic
clock for various operations that calculate and use elapsed duration.
The latter is preferable because in some cases `Time.now` can be
unstable, like if it's set manually by a system administrator or an NTP
daemon.
I don't expect that the previous code would actually have caused trouble
in the vast majority of normal situations, so I'm not going to backport
anything, but this seems like good hygiene.
For better or worse I had to wrap the monotonic time calls in a new
`Util` function because (1) the normal invocation is long enough to have
caused a lot of overruns on our 80 character line lengths, and (2)
Timecop doesn't stub the monotonic clock, so the `Util` method gives us
a nice place that we can stub on where …
> Move to monotonic time for duration calculations

- Gemfile
- lib/stripe/util.rb
- test/stripe/stripe_client_test.rb
- test/test_helper.rb
If #857 comes in, it turns out that we don't need Timecop anymore (it
doesn't freeze the monotic clock, so I had to find another way) -- here
we remove all mentions of it and drop the dependency.
I don't find it causes too much trouble so I'm not against bringing it
back in the future if we need it again, but it seems good for project
cleanliness to take it out for now.
r? @ob-stripe
> Drop Timecop dependency

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
Provide nice errors for more types of network exceptions
`EOFError`
`Errno::ECONNRESET`
`Errno::ETIMEDOUT`
`Errno::EHOSTUNREACH`
> User-friendly messages for EOFError network errors

- .rubocop.yml
One thing I tend to do a lot is create little test scripts to help debug
or reproduce problems with stripe-ruby. The problem is that they get
picked up by Rubocop, produce a whole bunch of errors, and then make it
more difficult if my changes to actual library files are producing
problems.
Here I exclude these by introducing a convention for having them start
with `example_*`. This isn't particularly great, but will work.
r? @ob-stripe You don't happen to know of a better way to do this off
hand do you?
> Exclude ephemeral test scripts from Rubocop linting

- lib/stripe/api_operations/request.rb
- test/stripe/api_resource_test.rb
Previously, if you specified a non-nil non-string opt value, like a
symbol for `idempotency_key`, you'd get a pretty user-unfriendly error
from `Net::HTTP`:
```
/Users/brandur/.rbenv/versions/2.4.5/lib/ruby/2.4.0/net/http/header.rb:21:in `block in initialize_http_header': undefined method `strip' for :foo:Symbol (NoMethodError)
```
Here, we introduce a new argument error that makes it a little easier
for someone to read. The impetus for the change is that we had an
internal product quality report where someone ran into this and was
confused.
I'm _pretty sure_ this change is backward compatible because `Net::HTTP`
would call `strip` on anything that was passed in as a value, and
generally just strings would support that. There may be some other less
common data type that was accidentally …
> Nicer error when specifying non-nil non-string opt value

- lib/stripe/api_operations/list.rb
- lib/stripe/list_object.rb
- test/stripe/list_object_test.rb
Previously, `#auto_paging_each` would always try to paginate forward,
even if it was clear based on the list's current filters that the user
had been intending to iterate backwards by specifying an `ending_before`
filter exclusively.
Here we implement backwards iteration by detecting this condition,
reversing the current list data, and making new requests for the
previous page (instead of the next one) as needed, which allows the user
to handle elements in reverse logical order.
Reversing the current page's list is intended as a minor user feature,
but may possibly be contentious. For background, when backwards
iterating in the API, results are still returned in "normal" order. So
if I specifying `ending_before=7`, the next page would look like `[4, 5,
6`] instead of `[6, 5, 4]`. In …
> Support backwards pagination with list's `#auto_paging_each`

- lib/stripe/api_operations/request.rb
- test/stripe/api_resource_test.rb
There are two kinds of API operations: collection and element specific.
The signature between the two is slightly different:
- **collection**: (params, opts)
- **element specific**: (id, params, opts)
If a user doesn't realize the difference, they may attempt to use the
collection signature when performing an element specific operation like:
```
Stripe::PaymentIntent.cancel('pi_1234', 'sk_test_key')
```
The resulting error message isn't very useful for debugging.
Instead,this PR adds a message letting the user know what it's expecting:
`request params should be either a Hash or nil (was a String)`
Addresses https://github.com/stripe/stripe-ruby/issues/855
> Raise an error when requests params are invalid

- README.md
Came across another issue (https://github.com/stripe/stripe-ruby/issues/871) where someone was confused by the per-request configuration syntax. 
Figured I would take a stab at adding some explicit documentation.
> Add additional per-request configuration documentation

- README.md
- lib/stripe/instrumentation.rb
- lib/stripe/stripe_client.rb
- test/stripe/instrumentation_test.rb
- test/stripe/stripe_client_test.rb
We used to insert `Faraday::Request::Instrumentation` (with a monkey patch) into our Faraday middleware stack to be able to instrument Stripe calls with [StatsD](https://github.com/Shopify/statsd-instrument). With Faraday being removed in version 5, this required some rework. This commit implements a simple callback system that can be used with any kind of instrumentation library.
Closes https://github.com/stripe/stripe-ruby/issues/795
> Add simple instrumentation callback

- lib/stripe/resources/source.rb
- lib/stripe/resources/subscription_item.rb
- test/stripe/source_transaction_test.rb
- test/stripe/subscription_item_test.rb
r? @ob-stripe 
As per https://github.com/stripe/stripe-python/pull/627
Not sure if 2020,1 was the right thing to do for the deprecation timeframe, didn't want to promise something far away and then have it be soon.
> Add list_usage_record_summaries and list_source_transactions

- README.md
> Fix non-hash comment in README

- lib/stripe/oauth.rb
- test/stripe/oauth_test.rb
Override API key when `client_secret` is passed as an argument to `OAuth.token`.
Fixes #866.
> Override API key with `client_secret` in `OAuth.token`

- .rubocop.yml
- Gemfile
Basically went through trying to make the whole stripe-ruby test run
Ruby 2.7 friendly. @dennisvdvliet got most of the internal stuff, but we
still have a couple external dependencies that are producing warning.
Here we upgrade Rubocop to 0.79, which curbs some warnings. A few lints
were moved and/or renamed, so I've modified the `.rubocop.yml`
appropriately, but there's no major changes there.
The last broken dependency is Webmock, and luckily I think it's pretty
easy to fix, so I'll send them a PR and see what happens.
r? @ob-stripe
> Upgrade Rubocop to 0.79

- test/stripe/source_test.rb
- test/stripe/usage_record_summary_test.rb
I just noticed while running tests that we produce some accidental
output because both of `Source#source_transactions` and
`SubscriptionItem#usage_record_summaries` are considered deprecated and
have warnings attached.
Here we capture output to `$stderr` and assert on it from the test cases
that call these deprecated methods -- this pattern is already well
established elsewhere in the test suite.
r? @ob-stripe
> Clean up test output by capturing `$stderr` when we expect warnings

- Gemfile
Bumps the minimum version of webmock to 3.8.0 which contains a fix for a
Ruby 2.7 warning. This last change makes the whole project completely
warning-free!
> Bump minimum version of webmock to 3.8.0

- README.md
Move examples to Customer instead of Charge. Also removed top-level mention of partial saves since we consider this actively deprecated
r? @ob-stripe 
> Move code examples from charge to customer

- README.md
- lib/stripe/instrumentation.rb
- lib/stripe/stripe_client.rb
- test/stripe/instrumentation_test.rb
- test/stripe/stripe_client_test.rb
Adds a new instrumentation callback called `request_begin` which, as the
name suggests, is invoked before an HTTP request is dispatched. As
outlined originally in #900, the idea is that this will enable a set of
hooks that can be used for distributed tracing.
The PR also renames the existing `request` callback to `request_end`,
although the old name is still invoked for the time being for backwards
compatibility.
A special `user_data` property is passed to `request_begin` which allows
subscribers to set custom data that will be passed through to
`request_end` for any given request. This allows, for example, a user
assigned ID to be set for the request and recognized on both ends.
I chose the naming `_begin` and `_end` (as opposed to start/finish or
any other combination) based on the …
> Add `request_begin` instrumentation callback

- .rubocop.yml
- Gemfile
- test/stripe/stripe_object_test.rb
Just noticed that a new version of Rubocop came out today. The upgrade
seemed relatively painless, so just went for it.
r? @ob-stripe
> Upgrade to Rubocop 0.80

- lib/stripe/errors.rb
- test/stripe/errors_test.rb
Adds an easy accessor on `StripeError` which indicates whether the error
occurred previously, but was replayed on this request because the user
passed the same idempotency key as that original request.
Fixes #905.
r? @ob-stripe
> Add `StripeError#idempotent_replayed?`

- Gemfile
Minor changes that locks us on the 2.0.0 release candidate for
`shoulda-context`. This makes almost no difference to our test suite
except that it removes a long-standing warning for an assigned but
unused variable.
See more context here:
https://github.com/thoughtbot/shoulda-context/issues/57#issuecomment-610702695
> Lock `shoulda-context` to 2.0.0rc4

- lib/stripe/webhook.rb
- test/stripe/webhook_test.rb
Exposes the `.compute_signature` method, which may be useful when
testing webhook signing in test suites.
I change the API slightly so that a caller isn't forced to do as much
string mangling, and to match the one that we already have in stripe-go:
``` go
func ComputeSignature(t time.Time, payload []byte, secret string) []byte {
```
Add basic documentation and test case. I also change a few things around
so that we send `Time` objects around more often where applicable, and
don't change then to Unix integers until the last moment that we need
to.
The one other alternative API I considered is this one, which would
default the timestamp to the current time to allow the method to be
called with one fewer arg:
``` ruby
def self.compute_signature(payload, secret, timestamp: Time.now)
```
I …
> Expose `Stripe::Webhook.compute_signature`

- lib/stripe/webhook.rb
- test/stripe/webhook_test.rb
Adds a new `generate_header` method for the webhooks module, following
up #915. This method doesn't help in any way with webhook verification,
but may be useful to users in their test suites as it allows them to
easily simulate the contents of a header that Stripe might have sent.
We briefly discussed an alternative design here, but this one seems like
the best fit:
https://github.com/stripe/stripe-ruby/pull/915#issuecomment-620164654
r? @ob-stripe
> Add new `.generate_header` method for webhooks

- .travis.yml
- test/stripe/account_link_test.rb
- test/test_helper.rb
The params for AccountLink changed in `v0.93.0`, which will cause the test suite to fail unless `stripe-mock` is pinned to an earlier version.
Fixes #934
> Update minimum stripe-mock version to 0.94.0

- .rubocop.yml
- lib/stripe/api_operations/create.rb
- lib/stripe/api_operations/delete.rb
- lib/stripe/api_operations/list.rb
- lib/stripe/api_operations/nested_resource.rb
- lib/stripe/api_operations/request.rb
- lib/stripe/api_operations/save.rb
- lib/stripe/api_resource.rb
- lib/stripe/list_object.rb
- lib/stripe/oauth.rb
- lib/stripe/resources/account.rb
- lib/stripe/resources/bank_account.rb
- lib/stripe/resources/credit_note.rb
- lib/stripe/resources/customer.rb
- lib/stripe/resources/invoice.rb
- lib/stripe/resources/source.rb
- lib/stripe/resources/subscription_item.rb
As seen in #928, the `refresh` method doesn't work for an event class.
This is because event has a field called `request`, and it ends up
replacing the `request` method that it inherited from being an API
resource, so when `refresh` tries to make a request, it fails because it
tries to invoke it on the accessor added for the event's property.
Here we give `request` a much more unique name so that it will never
conflict with a property field again, and update all internal references
to use the new name. We use `alias` to make the old name available for
backwards compatibility reasons because its been around for so long that
people are probably calling it.
Fixes #928.
r? @ob-stripe @richardm-stripe
> Rename API resource's `request` method

- lib/stripe.rb
- lib/stripe/stripe_configuration.rb
- test/stripe/stripe_configuration_test.rb
- test/stripe_test.rb
Adds a `Stripe::StripeConfiguration` object to manage internal and user supplied configuration options.
This is primarily motivated by [discussion](https://github.com/stripe/stripe-ruby/pull/921/files#r454611338) in #921 in order to provide a way to set options for an instance of `StripeClient`.
> Extract configurations into separate object

- .travis.yml
- lib/stripe/resources/issuing/dispute.rb
- test/stripe/api_resource_test.rb
- test/stripe/customer_card_test.rb
- test/stripe/issuing/dispute_test.rb
- test/test_helper.rb
The change is to add the new `/v1/issuing/disputes/idp_123/submit` endpoint but the tests needed to be fixed due to an ongoing stripe-mock issue around includable sub-lists.
Assigning to Brandur for familiarity with stripe-ruby and the current bug discussed in stripe-mock 
> Add support for the Issuing Dispute Submit API

- .travis.yml
- lib/stripe/resources/payout.rb
- test/stripe/customer_test.rb
- test/stripe/payout_test.rb
- test/test_helper.rb
Codegen for openapi 4bd4c01
r? @richardm-stripe 
> Add support for the Payout Reverse API

- README.md
- lib/stripe.rb
- lib/stripe/connection_manager.rb
- lib/stripe/stripe_configuration.rb
- test/stripe/connection_manager_test.rb
- test/stripe/stripe_configuration_test.rb
- test/stripe_test.rb
- test/test_helper.rb
See original Ruby issue: https://bugs.ruby-lang.org/issues/13396 and implementation: https://github.com/ruby/ruby/commit/bd7c46a7aa8b4f44ef683e22f469033b96d3dd5f
In Ruby 2.6+ this defaults to 60s. I picked 30 seconds to make it in line with `open_timeout`. IMO the defaults are too generous but that's a discussion for another time :)
> Allow setting write_timeout for connections on Ruby 2.6+

- lib/stripe.rb
While (re)working a PR to support `StripeClient` instances, I realized that it'd likely be desirable to set the `client_id` on the instance. Otherwise, users would always have to set the `client_id` on `Stripe` despite other configurations being provided when initializing a `StripeClient`.
Turns out, it's already set up and tested, but the `attr_accessor` on `Stripe` was still lingering;
Mostly breaking this out so the the `StripeClient` PR isn't as noisy :smile:
> Allow client_id configuration on instance config

- README.md
6 of 9 videos are now live covering how to use features of stripe-ruby. The remaining videos will be released over the coming weeks.
This adds a link to the YouTube playlist into the readme. Once we have all episodes live, I plan to add a description of each and links to the specific timestamps as part of the Wiki.
r? @ctrudeau-stripe
> Add playlist links into README

- lib/stripe/resources/customer.rb
- test/stripe/customer_test.rb
`Customer#delete_discount` has been broken for some time in that it
tries to re-initialize `self` (which is a customer) with a received
discount response. This is incorrect and leads to various problems.
Here, we redefine the return value of `delete_discount` as a discount,
and have it no longer mutate the object on which is was called. We add a
comment as well just to help flag some of the behavior which could
potentially be confusing.
Fixes #963.
r? @richardm-stripe
@richardm-stripe @remi-stripe I know there are some concerns around
backwards compatibility here, but given that anyone current trying to
use the return value of this method is pretty broken, and has been for a
while, I was thinking about just releasing it as a patch version. Any
objections?
> Fix return value of `Customer#delete_discount`

- .github/workflows/ci.yml
- Gemfile
- README.md
- test/test_helper.rb
r? @ob-stripe this is the last library!
- Adds a github actions ci workflow.
- Removes coveralls.
- `bundle exec rubocop` runs in Ruby 2.7.
- `bundle exec test` runs in all supported ruby versions.
- And a slightly newer version of JRuby than travis runs.
> CI: github actions

- lib/stripe.rb
- lib/stripe/connection_manager.rb
- lib/stripe/oauth.rb
- lib/stripe/resources/account.rb
- lib/stripe/resources/file.rb
- lib/stripe/stripe_client.rb
- lib/stripe/stripe_configuration.rb
- lib/stripe/util.rb
- test/stripe/connection_manager_test.rb
- test/stripe/oauth_test.rb
- test/stripe/stripe_client_test.rb
- test/stripe/stripe_configuration_test.rb
- test/stripe_test.rb
This changes allows for each instance of `StripeClient` to have its own
configuration object instead of relying on the global config. Each
instance can be configured to override any global config values
previously set.
> Allow StripeClient to be configured per instance

- lib/stripe/stripe_object.rb
- test/stripe/stripe_object_test.rb
When populating `StripeObject`s, we add accessors to them so that people
can access fields like `obj.currency`.
This was probably only meant to apply to API resources, but through
what might have been an accident of history, we've also traditionally
unmarshaled any hash that comes back from the API as a `StripeObject`,
including `metadata` fields. This allows some convenience because users
can access values like `obj.metadata.my_field`, but is also obviously a
minefield for potential problems.
In issue #969, what's essentially happening is that because there's a
metadata field named `class`, we've overwritten the object's normal
`class` method with our own custom one that accesses the metadata value.
Amazingly, the object can still marshal/unmarshal mostly properly, but
fails on this line …
> Reserve some critical field names when adding `StripeObject` accessors

- lib/stripe/stripe_client.rb
- lib/stripe/stripe_configuration.rb
- test/stripe/stripe_client_test.rb
- test/stripe/stripe_configuration_test.rb
Follows up #968.
As a relic from when we had global configuration, anytime any config value is changed on any client, we still clear all connection managers everywhere on every thread, even though this is not necessary. This means that we lose all open connections, etc.
Here, we make changes so that if a configuration is changed, we only clear the configuration managers pertaining to that one particular configuration, thus conserving resources globally.
@joeltaylor We've foisted enough work on you already, but if you'd like, feel free to take a look at this change set to make sure it's in-line with your implementation's principles.
> On config change, only clear connection managers for changed config

- lib/stripe.rb
- lib/stripe/connection_manager.rb
- lib/stripe/resources/file.rb
- lib/stripe/stripe_client.rb
- lib/stripe/util.rb
- test/stripe/stripe_client_test.rb
This is just a cosmetic change that renames `Stripe.configuration` to
just `Stripe.config`. We use the shorter "config" in most other places
including `StripeClient#config`, so I feel that this is overall more
consistent.
This change is backwards compatible because the new accessor came in
with #968, and that hasn't been given a formal release yet.
I've left the class name as `StripeConfiguration` which IMO is fine. The
class uses the expanded form of the name while vars and accessors use
the shorter `config`. Also, `StripeConfiguration` has been around a
little bit longer, so renaming it is somewhat backwards incompatible
too.
r? @richardm-stripe This one's pretty tiny. Mind taking a look?
> Rename `Stripe.configuration` to `Stripe.config`

- stripe.gemspec
This change aims to reduce the packed gem size by removing needless files from `s.files`.
Also, `s.test_files` is also removed because it is not defined in the gemspec reference.
(see <https://guides.rubygems.org/specification-reference/>)
- Size changed: 215K -> 264K
- Files changed: 221 files -> 120 files
> Reduce packed gem size

- lib/stripe/util.rb
- test/stripe/api_operations_test.rb
r? @richardm-stripe 
Updates `normalize_opts` to use `dup` instead of `clone` when copying the user-provided `opts`. This does not copy over the freeze state and avoids issues where internal classes (eg. `execute_request_internal`) receive frozen opts, normalize them, and then try to mutate them
Fixes https://github.com/stripe/stripe-ruby/issues/984
Added unit test to cover this case for regressions.
> Update normalize_opts to use dup instead of clone.

- lib/stripe/error_object.rb
r? @richardm-stripe 
Removes unused error types (`api_connection_error`, `authentication_error`, and `rate_limit_error`) from docstring.
> Remove unused API error types from docs.

- README.md
- lib/stripe/instrumentation.rb
- lib/stripe/stripe_client.rb
- test/stripe/instrumentation_test.rb
- test/stripe/stripe_client_test.rb
We'd like to trace back a request back to a particular request_id. To do this we'll need to pass the `request_id` to RequestEndEvent.
```#<Stripe::Instrumentation::RequestEndEvent:0x00007f8c3d231218
@duration=0.02757700002985075,
@http_status=200,
@method=:get,
@num_retries=0,
@path="/v1/charges/ch_sp_sale_charge",
@request_id='req_123',
@user_data={}>
```
Will the `request_id` always be available? What about scenarios where a request fails?
> Add `request_id` to RequestEndEvent

- lib/stripe/connection_manager.rb
- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
r? @richardm-stripe 
Adds extra logging details around the connection manager as well as begins including the following for exsiting requesting logs:
* response object ID
* thread ID
* process ID
* timestamp
This can help us track down cross-thread interaction in logs. This is all local logging (ie. this is not part of telemetry).
> Add connection manager logging and include object IDs in logging.

- stripe.gemspec
r? @dcr-stripe 
Changes the homepage and documentation URIs in  the `.gemspec` from `https://stripe.com/docs/api/ruby` (which returns HTTP 404) to `https://stripe.com/docs/api?lang=ruby`.
> Fix broken URIs in gemspec

- README.md
r? @yejia-stripe 
Updates the README URLs to https://stripe.com/docs/api to point to the correct URLs.
> Update Docs URLs in README.

- lib/stripe/resources/refund.rb
- test/stripe/generated_examples_test.rb
Codegen for openapi e07f049.
r? @pakrym-stripe (test_helpers expertise)
* Add support for `expire` test helper method on resource `Refund`
> API Updates

- lib/stripe/util.rb
- test/stripe/util_test.rb
r? @stripe/server-api-libraries-admins 
Updates our logging utilities to transform any string encoded as ASCII-8bit (raw binary) to UTF-8 when logging out. 
The strings returned from the server are in ASCII-8bit until the JSON marshaller transforms them to UTF-8. Unfortunately we have logging statements which pass the raw content sent back from the server. puts fails to interpret these as 8bit because they're actually utf-8 characters.
So, we force any binary string to actually be encoded as UTF-8 for the purposes of debug logging.
Alternatives:
1. We could do a more localized fix here just for the body, but my worry is this will then become a game of whack-a-mole and finding all of the logging calls which pass the raw body.  
2. We could potentially immediately encode the response …
> fix: Update logging to coerce ASCII-8BIT into UTF-8.

- lib/stripe.rb
- lib/stripe/api_version.rb
- lib/stripe/stripe_configuration.rb
- test/stripe/stripe_configuration_test.rb
To support generating beta header values, use the generated ApiVersion value instead of the hardcoded one.
This change applies to beta only.
r? @dcr-stripe
> Use the generated API version

- .rubocop.yml
r? @dcr-stripe 
Update rubocop config to allow some non-ASCII characters in comments.
> Update AllowedChars in rubocop config

- .github/workflows/ci.yml
- Gemfile
- README.md
- test/test_helper.rb
Add test coverage reporting to coveralls for Ruby version 3.1. Test coverage data will be published to https://coveralls.io/github/stripe/stripe-ruby and displayed as a badge in the README.
Example build: https://coveralls.io/builds/51915924
r? @dcr-stripe
> Add test coverage using Coveralls

- test/test_helper.rb
Do not run Coveralls step if the secret token does not exist (for pushes triggered by outside collaborators).
https://github.com/stripe/stripe-php/pull/1379 - make this change consistent across all languages
> Do not run Coveralls if secret token is not available

- lib/stripe/api_operations/save.rb
Mark `save()` method as deprecated.
> Deprecate save()

- .rubocop.yml
To support documentation that contains UTF-8 encoded characters, disable Rubocop's `Style/AsciiComments` rule. In the future we will want to upgrade Rubocop to a more recent version, since as of [1.21.0](https://github.com/rubocop/rubocop/issues/9674) this rule is disabled by default.
> Disable AsciiComments rule

- lib/stripe/api_version.rb
- lib/stripe/resources/subscription.rb
* Update current API version to 2022-11-09
* Remove deprecated `Subscription.delete`. Use `Subscription.cancel`.
> API Version 2022-11-09

- test/stripe/api_resource_test.rb
(Follow up to https://github.com/stripe/stripe-ruby/pull/1149)
Add `.update` tests in addition to `.save`, as `.save` is deprecated in favor of `.update`.
> Add tests for update

- lib/stripe/instrumentation.rb
- lib/stripe/stripe_client.rb
- test/stripe/instrumentation_test.rb
- test/stripe/stripe_client_test.rb
This is an extension of the simple instrumentation callback what has been done previously in https://github.com/stripe/stripe-ruby/pull/870.
To create our own event logs of Stripe calls, we were missing certain informations when we subscribe to `Request`/`RequestEnd`. The missing informations that we would like to have access to are:
- Request headers and body
- Response headers and body
We simply added the missing fields to the `RequestEndEvent` class.
Please correct me if I am wrong, but here is my understanding on where to retrieve the missing informations.
- Context seems to hold the information about the request
- `context.body` would hold the request body information
- Resp seems to be the response
- `resp.body` holds the response body
- `resp.to_hash` seems to hold the hidden …
> Improve request events instrumentation

- lib/stripe/stripe_object.rb
Grep indicates this is never used. The last usage was removed in #964. The method is `protected`, and so we can remove this unbreakingly.
> Remove unused `partial` param from `initialize_from`

- .github/workflows/ci.yml
- Makefile
Uses a shared stripe-mock action that has logic to load `beta` spec when needed.
> Use shared stripe-mock action

- test/stripe/source_test.rb
spec3.sdk doesn't have this method, it's added via overrides only for ruby.
> Remove test for a method without stripe-mock support

- lib/stripe/request_signing_authenticator.rb
- test/stripe/stripe_client_test.rb
Represent the sign method as a lambda for simpler `RequestSigningAuthenticator` creation.
> Accept sign as lambda function

- Gemfile
- lib/stripe/stripe_client.rb
- test/stripe/preview_test.rb
The error message can be returned in a `developer_message` field, handle this case and throw a useful error.
> Handle developer message in preview error responses

- README.md
This PR fixes what I believe is a typo in the README example for instrumentation. The variable's name doesn't seem to match.
> fix: variable typo in README for instrumentation

- lib/stripe/stripe_configuration.rb
"error" was introduced as a valid value for `LOG_LEVEL` in https://github.com/stripe/stripe-ruby/pull/1235. Update the error message to also reflect this.
> Update log level error message to include `error`

- lib/stripe/stripe_client.rb
- test/stripe/preview_test.rb
Preview error messages now contain a message field.
> Remove developer_message support

- lib/stripe/webhook.rb
When interpolating a Time object in a String, Ruby calls `to_s` under the hood.
For Rails applications defining a `default` string format, this triggers deprecation warnings as of v7.0.7: https://github.com/rails/rails/pull/48555
This change fixes that by explicitly formatting the timestamp (using the same `YYYY-MM-DD HH:mm:ss` format currently implicitly used).
> Explicitly format timestamp in SignatureVerificationError message

- lib/stripe.rb
- lib/stripe/api_operations/singleton_save.rb
- lib/stripe/resources/tax/settings.rb
- test/stripe/api_resource_test.rb
- test/stripe/generated_examples_test.rb
Singleton resources do not need the `id` parameter that method from `Stripe::APIOperations::Save` have.
> Add support for updatable singleton resources

- lib/stripe/resources/application_fee_refund.rb
- lib/stripe/resources/capability.rb
- lib/stripe/resources/customer_balance_transaction.rb
- lib/stripe/resources/customer_cash_balance_transaction.rb
- lib/stripe/resources/person.rb
- lib/stripe/resources/reversal.rb
- lib/stripe/resources/tax_id.rb
See #1316 for tests that prove that this is the case.
Removes list method mixin from child resources, as these methods always return `InvalidRequestError` and never succeed
> Remove list method in child resources

- lib/stripe/search_result_object.rb
There was an internal usages of the `Stripe::SearchResultObject#_search` method we deprecated in https://github.com/stripe/stripe-ruby/pull/1311.
https://github.com/stripe/stripe-ruby/issues/1319 can be resolved after this change goes out in the next release
> Remove internal usages of _search

- stripe.gemspec
Follow-up from comment that pointed out an issue after introducing sorbet in CI.
> Exclude sorbet directory and tapioca script when packing gem

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
This PR updates the retry behavior in the Ruby SDK to be the same as rest of our languages in terms of when to retry for errors with code >=500
From @richardm-stripe who lead this investigation previously
> The additional restrictions in stripe-go/stripe-ruby (don't bother retrying POST status=500) is a sensible optimization but the logic also misses some statuses (503/504/502) that possibly could succeed on retry. It's better for cases more granular than `>=500` to be captured in the logic that produces `x-stripe-should-retry` rather than to be hardcoded/maintained across 7+ official server SDKs, Terminal SDKs, direct integrations, etc.
Related Jira: https://jira.corp.stripe.com/browse/DEVSDK-1711
* When no `x-stripe-should-retry` header is set in the response, the library now retries …
> Retry for all error codes >= 500

- Makefile
The output to /dev/null was included so autoformatting would happen quietly in codegen CI. Rubocop fails if there are any violations, even if they're autocorrected.
> Revert Makefile change to allow autoformatting in codegen

- CHANGELOG.md
I missed cleaning up the changelog when making the release. This is a post release attempt in doing so. We would like to keep the changelog free of non user facing changes to reduce noise for users
> Remove entries from CHANGELOG.md that are not user facing

- .github/workflows/ci.yml
Ruby 3.3 was released on December 25th 2023, it's probably worth testing against now that 3.3.1 is out and fixes some longstanding issues.
> Add Ruby 3.3 to CI test matrix

- lib/stripe/resources/issuing/authorization.rb
This PR adds Ruby SDK support for automatically marking methods as deprecated. 
- Mark as deprecated the `approve` and `decline` methods in `lib/stripe/resources/issuing/authorization.rb`. Instead, [respond directly to the webhook request to approve an authorization](https://stripe.com/docs/issuing/controls/real-time-authorizations#authorization-handling).
> Deprecate Ruby methods based on OpenAPI spec

- Gemfile
Seems like `jaro_winkler` is not used anywhere even in dependency tree. I can't seem to bundle install `jaro_winkler:v1.5.4`. Once I upgrade to `1.5.6` it install seamlessly.
CI works with `1.5.6` and even after removing the dependency.
Do we have more context on this? Why was this introduced or where is it being used? Are we okay with removing this?
`bundle exec gem dependency` outputs:
```
Gem addressable-2.8.6
bundler (>= 1.0, < 3.0, development)
public_suffix (>= 2.0.2, < 6.0)
Gem ast-2.4.2
bacon (~> 1.2, development)
bacon-colored_output (>= 0, development)
coveralls (~> 0.8.23, development)
kramdown (>= 0, development)
rake (~> 12.3, development)
simplecov (>= 0, development)
yard (>= 0, development)
Gem bigdecimal-3.1.7
Gem bundler-2.1.2
Gem byebug-11.1.3
bundler (~> 2.0, …
```
> Removed jaro_winkler as a dependency

- lib/stripe/api_operations/nested_resource.rb
- test/stripe/api_operations_test.rb
- test/stripe/transfer_test.rb
Related: https://github.com/stripe/stripe-ruby/issues/1393
* Allow `Stripe::Transfer.retrieve_reversal()` to accept a params hash as the third argument, followed by opts. No changes to existing calls are necessary, but in a future major version this method will be updated to only accept params as the first argument.
> Pass params to transfer reversal

- .vscode/extensions.json
This PR updates the vscode extension recommendation to be `LoranKloeze.ruby-rubocop-revived`. The new extension supports auto-fixes.
> Use updated rubocop vscode extension

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
Resulting deprecation message reads like this:
```
NOTE: Stripe::StripeClient#request is deprecated; use the `last_response` property on the returned
resource (see https://github.com/stripe/stripe-ruby?tab=readme-ov-file#accessing-a-response-object
for usage examples) instead. It will be removed on or after 2024-06.
```
* Add deprecation warning for `StripeClient#request`. This helper method will be removed in a future major version. To access response objects, use the `last_response` property on the returned resource instead. Refer to [Accessing a response object](https://github.com/stripe/stripe-ruby?tab=readme-ov-file#accessing-a-response-object) in the README for usage details.
> Deprecate StripeClient#request

- lib/stripe/api_operations/nested_resource.rb
- lib/stripe/singleton_api_resource.rb
- test/stripe/api_operations_test.rb
- test/stripe/balance_test.rb
- test/stripe/transfer_test.rb
* Singleton `retrieve` method now requires `params` to be passed as the first argument. Existing calls to singleton `retrieve` method with only `opts` argument will have to be updated to account for the addition of `params` argument. 
```ruby
params = { expand: ["available"] }
opts = { stripe_account: "acct_123" }
Stripe::Balance.retrieve(opts)
Stripe::Balance.retrieve(params, opts)
```
> Singleton retrieve method now requires params to be passed as the first argument

- .github/workflows/ci.yml
Unblocking major release by removing jrubby from the test matrix due to the error in [CI](https://github.com/stripe/stripe-ruby/actions/runs/9651358562/job/26619031291).
Error message:
```
LoadError: load error: mize/cache_protocol -- java.lang.NoSuchMethodError: 'org.joni.Region org.joni.Region.newRegion(int, int)'
require at org/jruby/RubyKernel.java:1057
<main> at /home/runner/.rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/mize-0.4.1/lib/mize/cache_methods.rb:1
require at org/jruby/RubyKernel.java:1057
<main> at /home/runner/.rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/mize-0.4.1/lib/mize/memoize.rb:1
require at org/jruby/RubyKernel.java:1057
<main> at /home/runner/.rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/mize-0.4.1/lib/mize.rb:13
require at org/jruby/RubyKernel.java:1057 …
```
> Temporarily remove jruby from test matrix

- .github/workflows/ci.yml
- .gitignore
- Gemfile
- README.md
- test/test_helper.rb
Fixes CI failures caused in JRuby. 
JRuby was removed temporarily in this [PR](https://github.com/stripe/stripe-ruby/pull/1424).
> Remove coveralls and re-added JRuby

- .rubocop.yml
- README.md
- lib/stripe.rb
- lib/stripe/stripe_client.rb
- test/stripe/raw_request_test.rb
- test/stripe_test.rb
Add raw request to stripe-ruby GA. Previously only available to stripe-ruby beta. This is an alternative to using the old StripeClient.request to make these requests.
- Adds the ability to make raw requests to the Stripe API, by providing an HTTP method and url. This is an alternative to using `Stripe::APIResource.request(...)` to make custom requests, which is discouraged and will be broken in a future major version.
> Add `raw_request`

- lib/stripe.rb
- test/stripe/raw_request_test.rb
Didn't add usage to the request when merging yesterday. This fixes that.
> Add usage to raw_request call

- lib/stripe/api_operations/request.rb
After releasing `raw_request`, this method should be deprecated. This TODO comment to remove in the next major has been here for ages, we should finally take action now that a more visible alternative exists. Doesn't change any behavior besides logging the message below.
Tested locally by calling the function, shows up with:
```
NOTE: Stripe::Account#request is deprecated; use Stripe.raw_request instead. It will be removed on or after 2024-07.
```
> Add deprecation warning for `APIResource.request`

- CHANGELOG.md
This change wasn't merged in the major release. 
https://github.com/stripe/stripe-ruby/pull/1419#issuecomment-2232577425
> Fixed changelog for major release 12.0.0

- examples/meter_event_stream.rb
- examples/new_example.rb
- lib/stripe/api_resource.rb
- test/stripe/api_resource_test.rb
These should not be available to these resources. We should consider generating them per-resource instead in the future.
> Fail resource-based methods for next resources

- README.md
- lib/stripe/api_operations/request.rb
- lib/stripe/api_requestor.rb
- test/stripe/api_requestor_test.rb
- test/stripe/stripe_client_test.rb
These methods were deprecated years ago, and still remained in the API. We'd like to discourage their use as alternatives exist and we are changing requestor patterns.
Also updates the README for correct raw_request snippets.
* ⚠️ Remove `APIResource.request`. Instead, use `StripeClient.raw_request` now.
```ruby
Stripe::APIResource.request(:get, "/v1/endpoint", params, opts)
client = Stripe::StripeClient.new(...)
resp = client.raw_request(:get, "/v1/endpoint", params: params, opts: opts)
```
* ⚠️ Remove `StripeClient.connection_manager` (now `APIRequestor.connection_manager`). This was a legacy method from years ago.
> Remove deprecated methods and update raw_request README

- examples/stripe_webhook_handler.rb
- lib/stripe/util.rb
- test/stripe/v2_event_test.rb
The SDK uses object strings in the API response to decide what class to parse a resource returned from the Stripe API into.  Recently, the object string for the V2 event base class changed from "event" to "v2.core.event".  We have to update the SDK to match.
- Changed "event" to "v2.core.event" in util.rb convert_to_stripe_object_with_params
Verified using the `stripe_webhook_handler.rb` example with events triggered from and forwarded by the Stripe CLI
http://go/j/DEVSDK-2202
> Fix v2 event object name

- lib/stripe/stripe_client.rb
- test/stripe/stripe_client_test.rb
We already have `Stripe::Webhook.construct_event` available, and we believe that we may want to unify thin and snapshot event processing on StripeClient eventually. Thus, `parseSnapshotEvent` is not actually useful to add for users.
> Remove parseSnapshotEvent from StripeClient

- lib/stripe/resources/v2/billing/meter_event.rb
- lib/stripe/resources/v2/billing/meter_event_adjustment.rb
- lib/stripe/resources/v2/billing/meter_event_session.rb
- test/stripe/api_resource_test.rb
- test/stripe/stripe_service_test.rb
CI failures are expected because stripe-mock doesn't yet have the changes these this PR is responding to
- fixes a bug where the `object` property of the `MeterEvent`, `MeterEventAdjustment`, and `MeterEventSession` didn't match the server.
> update object tags for meter-related classes

- README.md
- lib/stripe/api_resource.rb
- test/stripe/api_resource_test.rb
This is somewhat of a bug report masked as a PR, since I'm not sure what I suggested is the desired solution based on the API design of `ApiResource.refresh`. If we think this is the best solution for now, I'm happy to add tests as well.
With the refactor of v13, there are now cases where `self` is not mutated in the call to refresh and instead a new object is returned. This change ensures that the new object is always returned by returning the result of refresh instead. 
This case happens when the else branch of this method is triggered.
https://github.com/stripe/stripe-ruby/blob/a2e2881c7cad5ebe5ad03c013521d01384ab77d9/lib/stripe/api_requestor.rb#L236-L244
This happens if you defined a custom object that extends APIResource. For example, at Shopify we have an object like so:
```ruby …
```
> Always return the result of APIResource#refresh in APIResource.retrieve

- lib/stripe/api_resource.rb
- test/stripe/api_resource_test.rb
A bug was introduced in v13.0.0 where we did not return the specific instance type if it wasn't available in our object mapping chart when a v1 resource was refreshed (custom resources). This addresses that.
* Fix bug in APIResource#refresh and APIResource#retrieve where they returned an instance of `StripeObject` for custom resources. They should now return the instance of the custom resource.
> Fix APIResource#retrieve bug not returning instance of custom resources

- .vscode/extensions.json
Solargraph works much better OOTB in VSCode and I've had much less trouble with it. I think it works better as a default suggestion.
> Update VSCode default extensions to use solargraph instead of ruby lsp

- lib/stripe/util.rb
- test/stripe/util_test.rb
https://github.com/stripe/stripe-ruby/issues/1485 revealed a bug with our nested array param encoding.
Confirmed the test failed before the fix, included `v1` in the test instead of the correct param name `a`.
> Fix incorrect key in param encoding

- lib/stripe/stripe_client.rb
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- test/stripe/list_object_test.rb
- test/stripe/search_result_object_test.rb
- test/stripe/stripe_client_test.rb
Reported in https://github.com/stripe/stripe-ruby/issues/1506 where requestor is nil in deserialized lists. Before, we did not persist the requestor through lists in the response. This meant that requests couldn't be made on returned resources inside the list.
This passes requestor through to all instances of convert_to_stripe_object where it was previously not, and adds some tests for this.
> Pass requestor to all deserialized objects including lists

- .github/workflows/ci.yml
Our test action ran on `ubuntu-latest` and tests against a range of ruby versions.  https://github.com/actions/runner-images/commit/976232da217887825e7541c2635bf39cbbf22654 updates `ubuntu-latest` to Ubuntu 24.04 which was causing stripe-ruby CI jobs to error out with `Error: Unavailable version 9.4.0.0 for jruby on ubuntu-24.04`.
- Changed runs-on value for Test job to `ubuntu-22.04`
> Pin ubuntu version in Test action

- lib/stripe.rb
- lib/stripe/stripe_client.rb
- lib/stripe/stripe_configuration.rb
- test/stripe/stripe_client_test.rb
- test/stripe/stripe_configuration_test.rb
Raised in https://github.com/stripe/stripe-ruby/issues/1511 - In our v13 migration guide, we mention that we use global configuration for options that are not available per StripeClient. This was not implemented for that release, this remedies that.
Adds a new fxn and tests to StripeConfiguration to initialize a client configuration with given options, with each option following the priority:
- If available as a client option:
- If provided, set as provided option
- Use StripeConfiguration default
- If not available as a client option (e.g.`enable_telemetry`, `open_timeout`)
- Use global configuration value
* Fixes bug where `StripeClient` was not falling back to global options for options that are not available to be set per-client
> Import global configuration for options not available on StripeClient options

- justfile
Codegen for ruby was failing because `just format` for ruby was creating too much output. It turns out that even during "quiet" mode, `rubocop` prints outs the things it corrects (which there are a _ton_ of during generation).
So we need to pipe everything to `/dev/null` so there's no printing at all. I've confirmed this all works locally!
- pipe formatting output to `/dev/null`
> pipe rubocop output to devnull

- lib/stripe/resources/invoice_line_item.rb
- test/stripe/invoice_line_item_test.rb
The `request_stripe_object` is undefined, fix parent class. Issue raised in https://github.com/stripe/stripe-ruby/issues/1535
Change parent class from `StripeObject` to `APIResource`, and add a test for invoice line item update
> Fix InvoiceLineItem parent class

- .rubocop.yml
The `/v1/invoices/upcoming/lines` endpoint is being removed soon. As a result, we've been removing codegen overrides to unblock upstream PRs. This means generated ruby methods are no longer valid for lints, which is failing our formatter during codegen. I'm excluding those files for now.
Additionally, an increase in the number of events have made our big event mapping method too long. I fixed excluded that file from linting in a private repo, but should have done it here instead.
- exclude invoice-related code from naming conventions temporarily
- add `event_types` to the method line length exclusions (which duplicates a change made in the private ruby repo that I should have made here)
> adjust lint rules

- test/stripe/invoice_test.rb
The `/v1/invoices/upcoming/lines` endpoint is being removed soon. As a result, this test is causing CI failures upstream. 
We don't need to change anything auto-generated; that'll get picked up when the spec is updated. These changes are purely for manual files.
- comment out test
> Fixed broken test caused by removing overrides for invoice/upcoming

- .rubocop.yml
I edited the rubocop config in https://github.com/stripe/stripe-ruby/pull/1542, causing a merge conflict here
- merge; no other changes
> fix ruby merge conflict for beta

- Gemfile
`jruby` does not support the `rbs` gem right now (https://github.com/ruby/rbs/issues/2067), and the newest release of `rbi` adds a dependency to the rbs gem. This locks the dependency for jruby only.
> Lock `rbi` gem version in jruby

- lib/stripe/errors.rb
- test/stripe/errors_test.rb
We don't provide this publicly for v2, removing for consistency.
Remove `idempotent_replayed` method
https://jira.corp.stripe.com/browse/DEVSDK-2040
* ⚠️ Remove the `idempotent_replayed?` method on `StripeError`
* The information is accessible indirectly via the raw response headers, `StripeResponse.http_headers`. For example, use `resource.last_response.http_headers['Idempotent-Replayed']`
> Remove public idempotent_replayed? method

- lib/stripe/events/v2_core_account_including_configuration_customer_capability_status_updated_event.rb
- lib/stripe/events/v2_core_account_including_configuration_customer_updated_event.rb
- lib/stripe/events/v2_core_account_including_configuration_merchant_capability_status_updated_event.rb
- lib/stripe/events/v2_core_account_including_configuration_merchant_updated_event.rb
- lib/stripe/events/v2_core_account_including_configuration_recipient_capability_status_updated_event.rb
- lib/stripe/events/v2_core_account_including_configuration_recipient_updated_event.rb
- lib/stripe/events/v2_core_account_including_identity_updated_event.rb
- lib/stripe/events/v2_core_account_including_requirements_updated_event.rb
- lib/stripe/events/v2_core_account_link_completed_event.rb
Manually creating PRs as automation is currently failing
Re-generating after the latest set of fixes in the codegen around fixing event names and related objects
Re-run code gen
> Fix event names and related objects

- .rubocop.yml
- README.md
- lib/stripe/stripe_object.rb
- lib/stripe/util.rb
- test/stripe/stripe_object_test.rb
- test/stripe/util_test.rb
The Ruby SDK has some weird behaviors where it turns all objects returned by the API into methods, including metadata which can contain keys that are nonstandard. This was causing issues once I added more explicit attributes, defining instance variables to keep our attribute accessors happy dynamically with keys that are nonstandard. Reported in https://github.com/stripe/stripe-ruby/issues/1564
Validate all keys are invalid and log+reject the ones that are not
* Validate all keys returned from the API, including custom response fields, to make sure they can be set in an instance variable
* We do not set instance variables for invalid field names (as defined by the [Ruby spec](https://ruby-doc.org/docs/ruby-doc-bundle/Manual/man-1.4/syntax.html#ident)). We recommend for custom hash map …
> Validate all instance variable keys returned from the API

- lib/stripe/services/v2/core/event_service.rb
- rbi/stripe/services/v2/core/event_service.rbi
As brought up in https://github.com/stripe/stripe-ruby/issues/1567, redefining attribute `object_id` is unsafe and triggers a warning. Rename the field to avoid this conflict.
Rename field `object_id` to `object_id_`
* ⚠️ Change name of parameter from `object_id` to `object_id_` on `Stripe::V2::Core::EventService::ListParams` to avoid conflict with Ruby native attribute, as found in https://github.com/stripe/stripe-ruby/issues/1567
> Rename `object_id` in V2::Core::EventService::ListParams to `object_id_`

- lib/stripe/api_operations/save.rb
- lib/stripe/api_operations/singleton_save.rb
- lib/stripe/api_requestor.rb
- lib/stripe/api_resource.rb
- lib/stripe/request_options.rb
- lib/stripe/resources/source.rb
- lib/stripe/stripe_object.rb
- test/stripe/api_resource_test.rb
- test/stripe/request_options_test.rb
- test/stripe/stripe_client_test.rb
After v13, custom options passing was not working in retrieve as it was pre-v13. This flows the options through in this and other requests that use the `execute_request_initialize_from` method.
This sets a new variable that is sent to refresh, then @opts is set by our normal request-sending which then sets the correct options on the object for future requests made on that object. We do NOT want to continue sending custom headers, so it still does not persist these custom options on the object after the request is sent.
Some important notes:
* Net::HTTP does NOT allow nested maps, so I've explicitly added comments to make it more clear how to flow options using these requests
* I've also fixed some other cases where we don't process the headers before making our …
> Explicitly pass through custom headers in retrieve

- .rubocop.yml
Generated tests will have a variable type after https://github.com/stripe/sdk-codegen/pull/2367 is merged.
Added an exception to excluded generated_examples_test.rb
> Added rubocop exclusion for generated tests

- .github/workflows/ci.yml
In order to keep supporting new versions of Ruby we need to test against them.
Added Ruby version `3.4` to CI workflow.
> Include new Ruby 3.4 in CI

- lib/stripe/api_operations/nested_resource.rb
Fix indentation when `end` doesn't match `do`, which raises a warning. Resolving https://github.com/stripe/stripe-ruby/pull/1403/files.
Overall no-op, just whitespace change
> Fix mismatched indentations in `nested_resource`

- test/stripe/api_requestor_test.rb
CI is failing in master since I kicked off the new stripe-mock release, due to some of these endpoints that were used in these tests being deleted. These tests were intended to stub away these requests but the endpoints are not all pointing to the same place.
Use the same default base address for all of the tests that were failing.
> Fix endpoints being hit since requests are stubbed

- lib/stripe/webhook.rb
- test/stripe/webhook_test.rb
Raised in https://github.com/stripe/stripe-ruby/issues/1616 -- fix `nil` APIRequestor for Event constructed from `Webhook`.
Global requestor is not passed into Webhook's `Event.construct_from`, fix that and also add test.
* Fix bug where `Event` constructed from `Webhook.construct_event` could not be refreshed due to a `nil` APIRequestor
* Raised in https://github.com/stripe/stripe-ruby/issues/1616
> Fix `nil` requestor in `Webhook.construct_event` to allow for event data refresh

- README.md
The README example for using `raw_request` is not valid.
Fixes the example usage of `raw_request` to pass `params` and `opts` as kwargs.
> Fix `raw_request` example in README

- test/stripe/api_requestor_test.rb
This test is flaky in jruby/truffleruby. Disable for now, as it sometimes blocks releases, until we have time to investigate more deeply.
> Disable flaky test in jruby/truffleruby

- README.md
We recommend using [StripeClient vs the legacy pattern](https://github.com/stripe/stripe-ruby?tab=readme-ov-file#stripeclient-vs-legacy-pattern). Our code snippets in readme should reflect the same
- Updated all snippets to use StripeClient
- Cleaned up parts of README not relevant anymore.
> Updated stripeclient snippets in Readme.md

- lib/stripe/api_version.rb
The Open API spec used to generate the SDK was using an older API version. The spec with the fix for this cannot be used as it also contains changes meant for the next release. Therefore, manually making the API version change here
Update API version 2025-08-04.private to 2025-08-27.preview
> Use the right API version 2025-08-27.preview

- lib/stripe/api_resource.rb
https://github.com/stripe/stripe-ruby/issues/1628#issuecomment-3128003410
Add a comment on the retrieve() method explaining how to pass parameters
> Add comment on retrieve on how to pass parameters

- CHANGELOG.md
Changelog wrongly points to basil instead of clover
Fix the API version in changelog
> Update CHANGELOG.md to point to right API version
